// This file is generated by scripts/generate_cloudflare_worker_js.py.
// Do not edit it by hand; edit config/default.yaml and regenerate.

export const DEFAULT_CONFIG = {
  "noon": {
    "华山论剑": {
      "战阵调整": [
        {
          "count": 8,
          "knights": [
            "林朝英",
            "王处一",
            "王重阳"
          ]
        },
        {
          "count": 4,
          "knights": [
            "龙岛主",
            "木岛主",
            "笑红尘"
          ]
        }
      ],
      "exchange": {
        "6857": {
          "material_name": "钻石",
          "quantity": 100
        },
        "6347": {
          "material_name": "侠士修身录",
          "quantity": 0
        },
        "6348": {
          "material_name": "侠士手记",
          "quantity": 0
        },
        "6349": {
          "material_name": "重出江湖令",
          "quantity": 0
        },
        "3090": {
          "material_name": "斗神符",
          "quantity": 0
        }
      }
    },
    "好友": {
      "乐斗次数": 20,
      "贡献药水": {
        "count": 4
      }
    },
    "侠侣": {
      "情师徒拜": {
        "enabled": true
      }
    },
    "群侠": {
      "设置战队": [
        "林朝英",
        "王处一",
        "王重阳",
        "木岛主",
        "龙岛主"
      ]
    },
    "巅峰之战进行中": {
      "id": 2
    },
    "矿洞": {
      "floor": 1,
      "mode": 1
    },
    "竞技场": {
      "河图洛书": {
        "enabled": true
      }
    },
    "十二宫": {
      "id": 1011
    },
    "历练": {
      "6114": 3,
      "6134": 2
    },
    "幻境": {
      "id": 20
    },
    "门派": {
      "门派高香": {
        "enabled": true
      },
      "门派战书": {
        "enabled": false
      }
    },
    "门派邀请赛": {
      "exchange": {
        "1246": {
          "material_name": "炼气石",
          "quantity": 0
        },
        "1247": {
          "material_name": "门派强化书",
          "quantity": 0
        },
        "1248": {
          "material_name": "门派高香",
          "quantity": 0
        },
        "1249": {
          "material_name": "门派战书",
          "quantity": 0
        },
        "1250": {
          "material_name": "门派引荐书",
          "quantity": 0
        }
      }
    },
    "会武": {
      "试炼书": {
        "enabled": true
      },
      "exchange": {
        "1263": {
          "material_name": "真黄金卷轴",
          "quantity": 20
        },
        "1264": {
          "material_name": "修为丹",
          "quantity": 0
        }
      }
    },
    "梦想之旅": {
      "梦幻旅行": {
        "count": 5
      }
    },
    "问鼎天下": {
      "region": 1,
      "count": 2,
      "淘汰赛": 96690,
      "排名赛": 96690
    },
    "帮派商会": {
      "交易会所": [
        "体力",
        "经验"
      ],
      "兑换商店": [
        "泯灭·黑炎V碎片"
      ]
    },
    "武林盟主": {
      "id": 1
    },
    "侠士客栈": {
      "黑市商人": null
    },
    "江湖长梦": {
      "exchange": {
        "0": {
          "material_name": "侠士修身录",
          "quantity": 0
        },
        "1": {
          "material_name": "侠士手记",
          "quantity": 0
        },
        "5": {
          "material_name": "玄铁令",
          "quantity": 0
        },
        "6": {
          "material_name": "淬火结晶",
          "quantity": 0
        },
        "10": {
          "material_name": "真黄金卷轴",
          "quantity": 0
        },
        "18": {
          "material_name": "石中剑",
          "quantity": 0
        },
        "19": {
          "material_name": "大型武器符咒",
          "quantity": 0
        },
        "20": {
          "material_name": "中型武器符咒",
          "quantity": 0
        },
        "21": {
          "material_name": "小型武器符咒",
          "quantity": 0
        },
        "22": {
          "material_name": "投掷武器符咒",
          "quantity": 0
        }
      }
    },
    "飞升大作战": {
      "玄铁令": {
        "enabled": true
      },
      "type": 1,
      "id": null
    },
    "深渊之潮": {
      "深渊秘境": {
        "count": 0,
        "id": 1
      },
      "exchange": {
        "5": {
          "material_name": "气魄之书",
          "quantity": 0
        },
        "6": {
          "material_name": "力魄之书",
          "quantity": 0
        },
        "7": {
          "material_name": "精魄之书",
          "quantity": 0
        },
        "8": {
          "material_name": "英魄之书",
          "quantity": 0
        },
        "9": {
          "material_name": "中枢之书",
          "quantity": 0
        },
        "10": {
          "material_name": "天冲之书",
          "quantity": 0
        },
        "11": {
          "material_name": "灵慧之书",
          "quantity": 0
        },
        "12": {
          "material_name": "佣兵天赋丹",
          "quantity": 0
        },
        "13": {
          "material_name": "许愿卡",
          "quantity": 0
        },
        "14": {
          "material_name": "五星许愿卡碎片",
          "quantity": 0
        },
        "15": {
          "material_name": "豆油队长碎片",
          "quantity": 0
        },
        "16": {
          "material_name": "定海制作书",
          "quantity": 0
        }
      }
    },
    "侠客岛": {
      "侠客行": [
        "侠士修身录*2",
        "侠士手记*2",
        "太玄经*2",
        "太玄经*1",
        "玄铁令*1"
      ]
    },
    "时空遗迹": {
      "八卦迷阵": "震巽坤离",
      "异兽洞窟": [
        5,
        4,
        3,
        2,
        1
      ],
      "exchange": {
        "4": {
          "material_name": "舆图",
          "quantity": 40,
          "type": 1
        },
        "8": {
          "material_name": "舆图",
          "quantity": 20,
          "type": 2
        },
        "1": {
          "material_name": "日引石",
          "quantity": 100,
          "type": 1
        },
        "2": {
          "material_name": "月引石",
          "quantity": 100,
          "type": 1
        },
        "3": {
          "material_name": "星引石",
          "quantity": 100,
          "type": 1
        },
        "5": {
          "material_name": "日引石",
          "quantity": 50,
          "type": 2
        },
        "6": {
          "material_name": "月引石",
          "quantity": 50,
          "type": 2
        },
        "7": {
          "material_name": "星引石",
          "quantity": 50,
          "type": 2
        }
      }
    },
    "龙凰之境": {
      "龙凰论武": {
        "id": 1,
        "count": 1
      },
      "exchange": {
        "1": {
          "material_name": "论武券",
          "quantity": 0
        },
        "2": {
          "material_name": "龙玉",
          "quantity": 0
        },
        "3": {
          "material_name": "凰髓",
          "quantity": 0
        },
        "4": {
          "material_name": "凰火",
          "quantity": 0
        }
      }
    },
    "我的帮派": {
      "帮战": {
        "enabled": false
      },
      "帮派供奉": [
        3043,
        3014,
        3028,
        3871,
        3001,
        3003,
        3074,
        3089
      ]
    },
    "客栈同福": {
      "献酒": [
        "王重阳碎片",
        "王处一碎片"
      ]
    },
    "节日福利": {
      "历练": {
        "enabled": true
      }
    },
    "双旦福利": {
      "历练": {
        "enabled": true
      }
    },
    "金秋福利": {
      "历练": {
        "enabled": true
      }
    },
    "春节福利": {
      "历练": {
        "enabled": true
      }
    },
    "多倍福利": {
      "历练": {
        "enabled": true
      }
    }
  },
  "evening": {
    "帮派商会": {
      "交易会所": [
        "体力",
        "经验"
      ],
      "兑换商店": [
        "泯灭·黑炎V碎片"
      ]
    },
    "侠士客栈": {
      "黑市商人": null
    },
    "江湖长梦": {
      "单次最大副本次数": 1,
      "柒承的忙碌日常": {
        "enabled": true,
        "material_name": "追忆香炉",
        "material_id": 6477
      },
      "群英拭剑谁为峰": {
        "enabled": false,
        "material_name": "拭剑香炉",
        "material_id": 6940
      },
      "时空守护者": {
        "enabled": false,
        "material_name": "时空香炉",
        "material_id": 6532
      },
      "倚天屠龙归我心": {
        "enabled": false,
        "material_name": "九阳香炉",
        "material_id": 6904
      },
      "神雕侠侣": {
        "enabled": false,
        "material_name": "盛世香炉",
        "material_id": 6476
      },
      "雪山藏魂": {
        "enabled": false,
        "material_name": "雪山香炉",
        "material_id": 8121
      },
      "桃花自古笑春风": {
        "enabled": false,
        "material_name": "桃花香炉",
        "material_id": 6825
      },
      "战乱襄阳": {
        "enabled": false,
        "material_name": "忠义香炉",
        "material_id": 6888
      },
      "天涯浪子": {
        "enabled": false,
        "material_name": "中秋香炉",
        "material_id": 6547
      },
      "全真古墓意难平": {
        "enabled": false,
        "material_name": "全真香炉",
        "material_id": 6662
      },
      "南海有岛名侠客": {
        "enabled": false,
        "material_name": "海岛香炉",
        "material_id": 6982
      },
      "老鹅的圣诞冒险": {
        "enabled": false,
        "material_name": "圣诞香炉",
        "material_id": 6609
      },
      "世外桃源梦一场": {
        "enabled": false,
        "material_name": "回梦香炉",
        "material_id": 6855
      },
      "中原武林之危": {
        "enabled": false,
        "material_name": "大宴香炉",
        "material_id": 6773
      },
      "世界树轮回秘境": {
        "enabled": false,
        "material_name": "树境香炉",
        "material_id": 8222
      },
      "技冠五绝": {
        "enabled": false,
        "material_name": "五绝香炉",
        "material_id": 8604
      }
    },
    "深渊之潮": {
      "深渊秘境": {
        "count": 0,
        "id": 1
      }
    },
    "龙凰之境": {
      "龙凰论武": {
        "count": 1
      }
    },
    "背包": {
      "最大扫描页数": 35,
      "最大使用次数": 10,
      "使用": [
        "盒",
        "包",
        "箱",
        "锦囊",
        "阅历",
        "信物",
        "勋章",
        "周年福袋",
        "大力丸",
        "活血散",
        "迅捷珠",
        "风之息",
        "神来拳套(赠)"
      ]
    },
    "吉利兑": {
      "exchange": {
        "5": {
          "material_name": "V级万能碎片",
          "quantity": 25
        },
        "6": {
          "material_name": "熔炼乌金",
          "quantity": 100
        },
        "7": {
          "material_name": "玄铁令",
          "quantity": 20
        },
        "8": {
          "material_name": "挑战书",
          "quantity": 30
        }
      }
    },
    "登录商店": {
      "id": 1225
    },
    "儿童节": {
      "id": "type=2&sub_type=2"
    },
    "开学季": {
      "id": "type=2&sub_type=2"
    },
    "生肖福卡": {
      "QQ": null
    },
    "客栈同福": {
      "献酒": [
        "王重阳碎片",
        "王处一碎片"
      ]
    },
    "节日福利": {
      "斗神塔": {
        "count": 16
      }
    },
    "双旦福利": {
      "斗神塔": {
        "count": 16
      }
    },
    "金秋福利": {
      "斗神塔": {
        "count": 16
      }
    },
    "春节福利": {
      "斗神塔": {
        "count": 16
      }
    },
    "多倍福利": {
      "斗神塔": {
        "count": 16
      }
    },
    "微信兑换": {
      "兑换码": 265151
    },
    "春联大赛": {
      "爆竹传吉语": "腊梅报新春",
      "爆竹欣祝福": "银蛇喜迎春",
      "爆竹欣祝褔": "银蛇乐报春",
      "春呈丰稔景": "酒贺小龙年",
      "春到田畴绿": "蛇来淑景新",
      "春归蛇起舞": "福到鸟争鸣",
      "春来千野绿": "蛇舞四时新",
      "除牙难捕鼠": "添足便成龙",
      "丁年歌盛世": "卯兔耀中华",
      "国强民幸福": "蛇舞世升平",
      "红梅迎春笑": "玉兔出月欢",
      "红梅迎雪放": "玉兔踏春来",
      "红梅赠虎岁": "彩烛耀兔年",
      "花放山河丽": "蛇迎世纪春",
      "花开四季馥": "蛇舞九州春",
      "花柳春风绿": "蛇年瑞气盈",
      "虎辟长安道": "兔开大吉春",
      "虎驰金世界": "兔唤玉乾坤",
      "虎带祥云去": "兔铺锦绣来",
      "虎年腾大步": "兔岁展宏图",
      "虎去雄风在": "兔来喜气浓",
      "虎声传捷报": "兔影抖春晖",
      "虎嘶飞雪里": "兔舞画图中",
      "虎蹄留胜迹": "兔角搏青云",
      "虎威惊盛世": "兔翰绘新春",
      "虎跃前程去": "兔携好运来",
      "虎留英雄气": "兔会世纪风",
      "捷报飞新宇": "春潮促小龙",
      "捷报书宏志": "春风乐小龙",
      "金虎辞旧岁": "银兔贺新春",
      "金蛇含瑞草": "紫燕报新春",
      "金蛇狂舞日": "紫燕报春时",
      "金蛇盘玉兔": "赤帜舞神州",
      "睛点龙飞去": "珠还蛇舞来",
      "龙去神威在": "蛇来紫气生",
      "龙蛇交替舞": "岁月又更新",
      "龙腾传捷报": "蛇舞兆丰年",
      "龙腾丰稔岁": "蛇舞吉庆年",
      "龙舞山河壮": "蛇盘世纪新",
      "龙吟山海壮": "蛇舞国民欢",
      "龙展强邦志": "蛇生富国情",
      "卯来四季美": "兔献百家福",
      "卯门生紫气": "兔岁报拜年",
      "卯时春入户": "兔岁喜盈门",
      "民逢大有岁": "国正小龙年",
      "瑞雪兆丰年": "迎得玉兔归",
      "山舞银蛇景": "梅香瑞雪春",
      "山舞银蛇日": "地披红杏时",
      "蛇酿新年酒": "花开盛世春",
      "蛇舞升平世": "莺歌富贵春",
      "笙歌辞旧岁": "兔酒庆新春",
      "兔归皓月亮": "花绽春光妍",
      "兔毫抒壮志": "燕梭织春光",
      "兔俊千山秀": "春暖万水清",
      "喜迎新世纪": "欢庆小龙年",
      "雪消狮子瘦": "月满兔儿肥",
      "燕舞春光丽": "兔奔曙光新",
      "寅年春锦绣": "卯序业辉煌",
      "玉兔蟾宫笑": "红梅五岭香",
      "玉兔迎春到": "红梅祝福来",
      "玉兔迎春至": "黄莺报喜来",
      "Q宠驭马闯新春": "侠士跟随巡江湖",
      "爆风逐蛇巡乐斗": "剑圣驱马守江山",
      "辞蛇年八方进宝": "迎马年四季发财",
      "辞蛇岁乐斗兴旺": "迎马年江湖昌隆",
      "鹅游乐斗随金蛇": "客聚江湖伴玉骢",
      "发财鹅迎蛇送福": "福马鹅接马添欢",
      "福马鹅驰追蛇影": "发财鹅跃逐马蹄",
      "金蛇点兵召佣兵": "福马点将唤神将",
      "金蛇启岁临乐斗": "福马迎春踏江川",
      "金蛇启运乐斗兴": "福马开泰江湖旺",
      "剑圣鹅随蛇辞旧": "精灵鹅伴马迎新",
      "乐斗聚贤逢蛇岁": "江湖结义遇马年",
      "龙脊承蛇安大陆": "蛇矛御马定江山",
      "灵蛇绕陆贺新岁": "神驹游湖庆吉年",
      "灵蛇佑侠平安岁": "骏马护将吉祥年",
      "青蛇点墨书新景": "白马挥毫绘锦天",
      "蛇矛映雪辉乐斗": "神弓凝霜耀江天",
      "蛇盘乐斗开鸿运": "马跃江湖纳吉缘",
      "蛇辞旧岁歌乐斗": "马迎新春笑江天",
      "蛇辞旧岁器魂盛": "马迎新春战力强",
      "蛇绕神弓呈吉兆": "马依龙脊展宏图",
      "蛇舞核弹惊天地": "马驰龙脊震乐斗",
      "蛇舞江湖凝器魂": "马驰乐斗聚侠心",
      "蛇游乐斗寻知己": "马走江湖结善缘",
      "神将摆摊卖撸串": "佣兵唠嗑送神装",
      "巳蛇纳福发财鹅": "午马迎祥福马鹅",
      "巳蛇送吉满大陆": "午马迎禧遍乐斗",
      "笑红尘歌蛇报喜": "福马鹅舞马呈安",
      "笑红尘随蛇纳福": "发财鹅伴马迎祥",
      "玉蛇衔福临洲岸": "金马驮祥踏浪澜"
    },
    "爱的同心结": {
      "QQ": null
    }
  }
};
