// This file is generated by scripts/generate_cloudflare_worker_js.py.
// Do not edit it by hand; edit src/tasks/*.py and regenerate.

import { DateTime, Registry, TaskModule, contains, pyAdd, pyAny, pyCount, pyDict, pyDivmod, pyEnumerate, pyGet, pyInt, pyIsSubset, pyItems, pyLen, pyMax, pyMin, pyRange, pySet, pySlice, pySorted, pyStr, pyTruthy, randomChoice, randomSample, sleep } from '../runtime.js';
async function c_get_material_quantity(d, item_id) {
  var number_str;
  await d.get(`cmd=owngoods&id=${item_id}`);
  if ((contains(d.html, "很抱歉"))) {
    return 0;
  }
  number_str = d.find("数量：(\\d+)");
  if ((number_str === null)) {
    return 0;
  }
  return pyInt(number_str);
}

async function c_get_doushenta_cd(d) {
  var cd, level;
  cd = ({["1"]: 7, ["2"]: 6, ["3"]: 5, ["4"]: 4, ["5"]: 3, ["6"]: 2, ["7"]: 1, ["8"]: 1, ["9"]: 1, ["10"]: 1});
  await d.get("cmd=ledouvip");
  if (pyTruthy((level = d.find("当前级别：(\\d+)")))) {
    return cd[level];
  } else {
    return 10;
  }
}

async function c_邪神秘宝(d) {
  var i;
  for (let i of [0, 1]) {
    await d.get(`cmd=tenlottery&op=2&type=${i}`);
    d.log(d.find("】</p>(.*?)<br />"));
  }
}

async function 帮派宝库(d) {
  var _id, data, t;
  for (let _ of pyRange(20)) {
    await d.get("cmd=fac_corp&op=0");
    data = d.findall("gift_id=(\\d+)&amp;type=(\\d+)\">点击领取");
    if (!pyTruthy(data)) {
      break;
    }
    for (let [_id, t] of data) {
      await d.get(`cmd=fac_corp&op=3&gift_id=${_id}&type=${t}`);
      d.log(`帮派宝库 -> ${d.find("</p>(.*?)<br />")}`);
      if ((contains(d.html, "恭喜您领取了"))) {
        continue;
      }
      return;
    }
  }
}

async function 交易会所(d) {
  var _id, config, material_name, t;
  config = d.config("帮派商会.交易会所");
  if ((config === null)) {
    return;
  }
  await d.get("cmd=fac_corp&op=1");
  if ((contains(d.html, "已交易"))) {
    return;
  }
  for (let [material_name, t, _id] of d.findall("要(.*?)，.*?type=(\\d+)&amp;goods_id=(\\d+)")) {
    if (!pyTruthy(pyAny(config, (i) => (contains(material_name, i))))) {
      continue;
    }
    await d.get(`cmd=fac_corp&op=4&type=${t}&goods_id=${_id}`);
    d.log(`${material_name} -> ${d.find("</p>(.*?)<br />")}`);
  }
}

async function 兑换商店(d) {
  var _id, config, material_name;
  config = d.config("帮派商会.兑换商店");
  if ((config === null)) {
    return;
  }
  await d.get("cmd=fac_corp&op=2");
  if ((contains(d.html, "已兑换"))) {
    return;
  }
  for (let [material_name, _id] of d.findall("</a><br />(.*?)&.*?type_id=(\\d+)")) {
    if (!pyTruthy(pyAny(config, (i) => (contains(material_name, i))))) {
      continue;
    }
    await d.get(`cmd=fac_corp&op=5&type_id=${_id}`);
    d.log(d.find("</p>(.*?)<br />"));
  }
}

async function c_帮派商会(d) {
  await 帮派宝库(d);
  await 交易会所(d);
  await 兑换商店(d);
}

async function c_任务派遣中心(d) {
  var A_ids, B_ids, S_ids, _id, _ids, accept_count, accept_limit, fail_ids, info, is_has_free_refresh_count, is_maximums, progress, task_name;
  await d.get("cmd=missionassign&subtype=0");
  for (let _id of d.findall("0时0分.*?mission_id=(.*?)\">查看")) {
    await d.get(`cmd=missionassign&subtype=1&mission_id=${_id}`);
    task_name = d.find("任务名称：(.*?)<");
    await d.get(`cmd=missionassign&subtype=5&mission_id=${_id}`);
    d.log(`${task_name} -> ${d.find("\\[任务派遣中心\\](.*?)<br />")}`);
  }
  fail_ids = pySet();
  is_maximums = false;
  is_has_free_refresh_count = true;
  for (let _ of pyRange(20)) {
    await d.get("cmd=missionassign&subtype=0");
    progress = d.findall("今日可接受：(\\d+)/(\\d+)");
    if (pyTruthy(progress)) {
      accept_count = pyInt(progress[0][0]);
      accept_limit = pyInt(progress[0][1]);
      if ((accept_count >= accept_limit)) {
        is_maximums = true;
        break;
      }
    }
    S_ids = d.findall("-S&nbsp;所需时间.*?_id=(\\d+)\">接受");
    A_ids = d.findall("-A&nbsp;所需时间.*?_id=(\\d+)\">接受");
    B_ids = d.findall("-B&nbsp;所需时间.*?_id=(\\d+)\">接受");
    _ids = pyAdd(S_ids, A_ids);
    if (!pyTruthy(is_has_free_refresh_count)) {
      _ids = pyAdd(pyAdd(S_ids, A_ids), B_ids);
    }
    if ((!pyTruthy(_ids) || pyTruthy(pyIsSubset(pySet(_ids), fail_ids)))) {
      if (pyTruthy(is_has_free_refresh_count)) {
        await d.get("cmd=missionassign&subtype=0");
        if ((contains(d.html, "本次消耗：0斗豆"))) {
          await d.get("cmd=missionassign&subtype=3");
          d.log("刷新任务 -> 免费刷新成功");
          continue;
        }
        d.log("刷新任务 -> 没有免费刷新次数了");
        is_has_free_refresh_count = false;
        continue;
      }
      break;
    }
    for (let _id of _ids) {
      await d.get(`cmd=missionassign&subtype=2&mission_id=${_id}`);
      task_name = d.find("任务名称：(.*?)<");
      await d.get(`cmd=missionassign&subtype=7&mission_id=${_id}`);
      if ((!contains(d.html, "设置佣兵成功"))) {
        d.log(`${task_name} -> ${d.find("】<br /><br />(.*?)<")}`);
        fail_ids.add(_id);
        continue;
      }
      d.log(`${task_name} -> ${d.find("】</p>(.*?)<")}`);
      await d.get(`cmd=missionassign&subtype=8&mission_id=${_id}`);
      if ((contains(d.html, "当前可执行任务数已达上限"))) {
        d.log(`${task_name} -> ${d.find("】<br /><br />(.*?)<")}`);
        is_maximums = true;
        break;
      }
      d.log(`${task_name} -> ${d.find("】</p>(.*?)<")}`);
      if (((pyCount(d.html, "查看") === 3) || (contains(d.html, "今日已领取了全部任务")))) {
        is_maximums = true;
        break;
      }
    }
    if (pyTruthy(is_maximums)) {
      break;
    }
    if (!pyTruthy(is_has_free_refresh_count)) {
      continue;
    }
    await d.get("cmd=missionassign&subtype=0");
    if ((contains(d.html, "本次消耗：0斗豆"))) {
      await d.get("cmd=missionassign&subtype=3");
      d.log("刷新任务 -> 免费刷新成功");
    } else {
      d.log("刷新任务 -> 没有免费刷新次数了");
      is_has_free_refresh_count = false;
    }
  }
  await d.get("cmd=missionassign&subtype=0");
  for (let info of d.findall("<br />(.*?)&nbsp;<a.*?查看")) {
    d.log(`当前任务 -> ${info}`);
  }
}

async function c_领取今日活跃度奖励(d) {
  var activity_level, giftbag_id, giftbag_ids, received_ids;
  await d.get("cmd=liveness");
  activity_level = d.find("今日活跃度：(\\d+)");
  if ((activity_level !== null)) {
    d.log(activity_level);
  }
  if ((contains(d.html, "帮派总活跃"))) {
    d.log(d.find("帮派总活跃：(.*?)<"));
  }
  await d.get("cmd=liveness_getgiftbag&action=0");
  giftbag_ids = d.findall("giftbagid=(\\d+)(?:&amp;|&)action=1");
  if (!pyTruthy(giftbag_ids)) {
    d.log("没有可领取今日活跃度礼包");
  } else {
    received_ids = pySet();
    for (let giftbag_id of giftbag_ids) {
      if ((contains(received_ids, giftbag_id))) {
        continue;
      }
      received_ids.add(giftbag_id);
      await d.get(`cmd=liveness_getgiftbag&giftbagid=${giftbag_id}&action=1`);
      d.log(d.find("】<br />(.*?)<p>"));
    }
  }
  await d.get("cmd=factionop&subtype=18");
  if ((contains(d.html, "创建帮派"))) {
    d.log(d.find("帮派</a><br />(.*?)<br />"));
  } else {
    d.log(d.find());
  }
}

async function c_侠士客栈(d) {
  var config, n, p, t, text;
  await d.get("cmd=warriorinn");
  for (let [t, n] of d.findall("type=(\\d+)&amp;num=(\\d+)")) {
    await d.get(`cmd=warriorinn&op=getlobbyreward&type=${t}&num=${n}`);
    d.log(d.find("侠士客栈<br />(.*?)<br />"));
  }
  for (let p of d.findall("pos=(\\d+)\">前来捣乱的")) {
    await d.get(`cmd=warriorinn&op=exceptadventure&pos=${p}`);
    d.log(d.find("侠士客栈<br />(.*?)<"));
  }
  config = d.config("侠士客栈.黑市商人");
  if ((config === null)) {
    return;
  }
  for (let p of d.findall("pos=(\\d+)\">黑市商人")) {
    await d.get(`cmd=warriorinn&op=confirmadventure&pos=${p}&type=0`);
    for (let text of config) {
      if ((contains(d.html, text))) {
        d.log(d.find("物品交换<br /><br />(.*?)<br />"));
        await d.get(`cmd=warriorinn&op=exceptadventure&pos=${p}`);
        d.log(d.find("侠士客栈<br />(.*?)<br />"));
      }
    }
  }
}

async function c_帮派巡礼(d) {
  await d.get("cmd=abysstide&op=getfactiongift");
  d.log(d.find());
}

async function c_深渊秘境(d) {
  var _id, count, exchange_count;
  exchange_count = d.config("深渊之潮.深渊秘境.count");
  _id = d.config("深渊之潮.深渊秘境.id");
  for (let _ of pyRange(exchange_count)) {
    await d.get("cmd=abysstide&op=addaccess");
    d.log(d.find());
    if ((contains(d.html, "无法继续兑换挑战次数"))) {
      break;
    }
  }
  await d.get("cmd=abysstide&op=viewallabyss");
  count = d.find("副本次数：(\\d+)");
  if ((count === null)) {
    d.log("获取副本次数失败");
    return;
  }
  for (let _ of pyRange(pyInt(count))) {
    await d.get(`cmd=abysstide&op=enterabyss&id=${_id}`);
    if ((!contains(d.html, "开始挑战"))) {
      break;
    }
    for (let _ of pyRange(5)) {
      await d.get("cmd=abysstide&op=beginfight");
      d.log(d.find());
      if ((contains(d.html, "憾负于"))) {
        break;
      }
    }
    await d.get("cmd=abysstide&op=endabyss");
    d.log(d.find());
  }
}

async function c_龙凰论武(d) {
  var _idx, count, data, uin;
  if (!pyTruthy((4 <= DateTime.day() && DateTime.day() <= 25))) {
    return;
  }
  await d.get("cmd=dragonphoenix&op=lunwu");
  if ((contains(d.html, "已报名"))) {
    d.log("系统已随机报名，次日才能挑战");
    return;
  } else if ((!contains(d.html, "论武榜"))) {
    d.log("进入论武异常，无法挑战");
    return;
  }
  count = d.config("龙凰之境.龙凰论武.count");
  for (let _ of pyRange(count)) {
    data = d.findall("uin=(\\d+).*?idx=(\\d+)");
    [uin, _idx] = randomChoice(data);
    await d.get(`cmd=dragonphoenix&op=pk&zone=1&uin=${uin}&idx=${_idx}`);
    d.log(d.find("/\\d+</a><br /><br />(.*?)<"));
    if ((contains(d.html, "挑战次数不足"))) {
      break;
    } else if ((contains(d.html, "冷却中"))) {
      break;
    }
  }
}

async function c_客栈同福(d) {
  var config, count, is_libation, pattern;
  config = d.config("客栈同福.献酒");
  if ((config === null)) {
    d.log("你没有设置出现字符");
    return;
  }
  await d.get("cmd=newAct&subtype=154");
  count = d.find("现有黄酒数量：(\\d+)");
  if ((count === null)) {
    d.log("获取黄酒数量失败");
    return;
  }
  if ((count === "0")) {
    d.log("黄酒数量不足");
    return;
  }
  is_libation = false;
  for (let _ of pyRange(pyInt(count))) {
    for (let pattern of config) {
      await d.get("cmd=newAct&subtype=154");
      if ((!contains(d.html, pattern))) {
        continue;
      }
      is_libation = true;
      await d.get("cmd=newAct&subtype=155");
      d.log(d.find("】<br /><p>(.*?)<br />"));
      if ((contains(d.html, "黄酒不足"))) {
        return;
      }
    }
    if (!pyTruthy(is_libation)) {
      d.log("没有找到匹配，本次无操作");
      break;
    }
  }
}

async function c_幸运金蛋(d) {
  var i;
  await d.get("cmd=newAct&subtype=110&op=0");
  if (pyTruthy((i = d.find("index=(\\d+)")))) {
    await d.get(`cmd=newAct&subtype=110&op=1&index=${i}`);
    d.log(d.find("】<br /><br />(.*?)<br />"));
  } else {
    d.log("没有砸蛋次数或者时间已过");
  }
}

async function c_大笨钟(d) {
  await d.get("cmd=newAct&subtype=18");
  d.log(d.find("<br /><br /><br />(.*?)<br />"));
}

const __globals = { c_get_material_quantity: c_get_material_quantity, c_get_doushenta_cd: c_get_doushenta_cd, c_邪神秘宝: c_邪神秘宝, 帮派宝库: 帮派宝库, 交易会所: 交易会所, 兑换商店: 兑换商店, c_帮派商会: c_帮派商会, c_任务派遣中心: c_任务派遣中心, c_领取今日活跃度奖励: c_领取今日活跃度奖励, c_侠士客栈: c_侠士客栈, c_帮派巡礼: c_帮派巡礼, c_深渊秘境: c_深渊秘境, c_龙凰论武: c_龙凰论武, c_客栈同福: c_客栈同福, c_幸运金蛋: c_幸运金蛋, c_大笨钟: c_大笨钟 };
export { c_get_material_quantity, c_get_doushenta_cd, c_邪神秘宝, 帮派宝库, 交易会所, 兑换商店, c_帮派商会, c_任务派遣中心, c_领取今日活跃度奖励, c_侠士客栈, c_帮派巡礼, c_深渊秘境, c_龙凰论武, c_客栈同福, c_幸运金蛋, c_大笨钟 };
