// This file is generated by scripts/generate_cloudflare_worker_js.py.
// Do not edit it by hand; edit src/tasks/*.py and regenerate.

import { DateTime, Registry, TaskModule, contains, pyAdd, pyAny, pyCount, pyDict, pyDivmod, pyEnumerate, pyGet, pyInt, pyIsSubset, pyItems, pyLen, pyMax, pyMin, pyRange, pySet, pySlice, pySorted, pyStr, pyTruthy, randomChoice, randomSample, sleep } from '../runtime.js';
import { c_get_material_quantity, c_get_doushenta_cd, c_邪神秘宝, c_帮派商会, c_任务派遣中心, c_侠士客栈, c_帮派巡礼, c_深渊秘境, c_龙凰论武, c_幸运金蛋, c_客栈同福, c_大笨钟 } from './common.js';

const registry = new Registry(TaskModule.evening);
const register = (taskName, taskFunc) => registry.register(taskName, taskFunc);
async function 邪神秘宝(d) {
  await c_邪神秘宝(d);
}

register("邪神秘宝", 邪神秘宝);

async function 星盘(d) {
  var data, g, material_name, need, possess, t;
  if ((DateTime.week() !== 4)) {
    return;
  }
  for (let t of pyRange(1, 9)) {
    await d.get(`cmd=astrolabe&op=showgemupgrade&gem_type=${t}`);
    data = d.findall("<br />=(.*?)=.*?gem=(\\d+).*?(\\d+) （(\\d+)");
    for (let [material_name, g, need, possess] of pySlice(data, 1, 4)) {
      for (let _ of pyRange(Math.floor(pyInt(possess) / pyInt(need)))) {
        await d.get(`cmd=astrolabe&op=upgradegem&gem_type=${t}&gem=${g}`);
        d.log(`${material_name} -> ${d.find()}`);
      }
    }
  }
}

register("星盘", 星盘);

async function 帮派商会(d) {
  await c_帮派商会(d);
}

register("帮派商会", 帮派商会);

async function 任务派遣中心(d) {
  await c_任务派遣中心(d);
}

register("任务派遣中心", 任务派遣中心);

async function 侠士客栈(d) {
  await c_侠士客栈(d);
}

register("侠士客栈", 侠士客栈);

async function _run_dream_instance(d, name, ins_id, material_quantity, duration, handle_day) {
  var current_name, day;
  for (let _ of pyRange(material_quantity)) {
    await d.get(`cmd=jianghudream&op=beginInstance&ins_id=${ins_id}`);
    d.log("开启副本", name);
    if ((contains(d.html, "帮助"))) {
      return;
    }
    if (pyTruthy((current_name = d.find("你在(.*?)共度过了")))) {
      d.log(`${name}: 请先手动完成 ${current_name}`, name);
      return;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      if ((contains(d.html, "进入下一天"))) {
        await d.get("cmd=jianghudream&op=goNextDay");
        day = pyAdd(day, 1);
      } else {
        d.log("请先手动通关剩余天数", name);
        return;
      }
      if (pyTruthy(await handle_day(day))) {
        await d.get("cmd=jianghudream&op=endInstance");
        d.log(d.find(), name);
        return;
      }
    }
    await d.get("cmd=jianghudream&op=endInstance");
    d.log(d.find(), name);
  }
  await d.get(`cmd=jianghudream&op=getFirstReward&ins_id=${ins_id}`);
  d.log(d.find(), name);
}

class JiangHuDream {
  constructor(d, name, ins_id) {
    this.d = d;
    this.name = name;
    this.ins_id = ins_id;
  }
  async begin_success() {
    var current_name;
    await this.d.get(`cmd=jianghudream&op=beginInstance&ins_id=${this.ins_id}`);
    this.d.log("开启副本", this.name);
    if ((contains(this.d.html, "帮助"))) {
      return false;
    }
    if (pyTruthy((current_name = this.d.find("你在(.*?)共度过了")))) {
      this.d.log(`请先手动完成 ${current_name}`, this.name);
      return false;
    }
    return true;
  }
  async next_day(day) {
    if ((contains(this.d.html, "进入下一天"))) {
      await this.d.get("cmd=jianghudream&op=goNextDay");
      day = pyAdd(day, 1);
      return day;
    }
    this.d.log("请先手动通关剩余天数", this.name);
  }
  async choose_fight(day, event_id) {
    await this.d.get(`cmd=jianghudream&op=chooseEvent&event_id=${event_id}`);
    await this.d.get("cmd=jianghudream&op=doPveFight");
    this.d.log(`第 ${day} 天 -> ${this.d.find("<p>(.*?)<br />")}`, this.name);
    if ((contains(this.d.html, "战败"))) {
      return false;
    }
    return true;
  }
  async choose_adventure(day, event_id, adventure_ids) {
    var _id;
    await this.d.get(`cmd=jianghudream&op=chooseEvent&event_id=${event_id}`);
    this.d.log(`第 ${day} 天 -> ${this.d.find("获得金币：\\d+<br />(.*?)<br />")}`, this.name);
    for (let _id of adventure_ids) {
      await this.d.get(`cmd=jianghudream&op=chooseAdventure&adventure_id=${_id}`);
      this.d.log(`第 ${day} 天 -> ${this.d.find("获得金币：\\d+<br />(.*?)<br />")}`, this.name);
    }
  }
  async choose_store() {
    var event_id;
    if (pyTruthy((event_id = this.d.find("event_id=(\\d+)\">商店")))) {
      await this.d.get(`cmd=jianghudream&op=chooseEvent&event_id=${event_id}`);
    }
  }
  async end_memories() {
    await this.d.get("cmd=jianghudream&op=endInstance");
    this.d.log(this.d.find(), this.name);
    await this.d.get(`cmd=jianghudream&op=getFirstReward&ins_id=${this.ins_id}`);
    this.d.log(this.d.find(), this.name);
  }
}

async function 柒承的忙碌日常(d, name, ins_id, material_quantity, duration) {
  var day, event_id, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_id = d.find("event_id=(\\d+)\">战斗")))) {
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇")))) {
        await j.choose_adventure(day, event_id, [2]);
        continue;
      }
      await j.choose_store();
    }
    await j.end_memories();
  }
}

async function 群英拭剑谁为峰(d, name, ins_id, material_quantity, duration) {
  var day, event_id, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_id = d.find("event_id=(\\d+)\">战斗\\(等级2\\)")))) {
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      }
    }
    await j.end_memories();
  }
}

async function 时空守护者(d, name, ins_id, material_quantity, duration) {
  var _ids, adventur, adventure_ids, day, event_id, event_ids, j, k;
  adventur = ({["上前询问"]: [1, 1], ["解释身份"]: [2, 1], ["原地思考"]: [2, 3], ["放她回去"]: [1]});
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_id = d.find("event_id=(\\d+)\">战斗\\(等级2\\)")))) {
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_ids = d.findall("event_id=(\\d+)\">战斗\\(等级1\\)")))) {
        if ((contains(pySet([2, 4]), day))) {
          event_id = event_ids[(-1)];
        } else {
          event_id = event_ids[0];
        }
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_ids = d.findall("event_id=(\\d+)\">奇遇\\(等级2\\)")))) {
        if ((day === 5)) {
          event_id = event_ids[(-1)];
        } else {
          event_id = event_ids[0];
        }
        adventure_ids = [];
        for (let [k, _ids] of pyItems(adventur)) {
          if ((contains(d.html, k))) {
            adventure_ids = _ids;
            break;
          }
        }
        await j.choose_adventure(day, event_id, adventure_ids);
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级1\\)")))) {
        if ((contains(d.html, "转一次"))) {
          adventure_ids = [3];
        } else if ((contains(d.html, "漩涡1"))) {
          adventure_ids = [1];
        } else {
          adventure_ids = [];
        }
        await j.choose_adventure(day, event_id, adventure_ids);
      } else {
        await j.choose_store();
      }
    }
    await j.end_memories();
  }
}

async function 倚天屠龙归我心(d, name, ins_id, material_quantity, duration) {
  var adventure_ids, day, event_id, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_id = d.find("event_id=(\\d+)\">战斗\\(等级2\\)")))) {
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">战斗\\(等级1\\)")))) {
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级2\\)")))) {
        if ((contains(pySet([1, 3, 7]), day))) {
          adventure_ids = [1];
        } else if ((contains(pySet([6, 8]), day))) {
          adventure_ids = [3];
        } else {
          adventure_ids = [];
        }
        await j.choose_adventure(day, event_id, adventure_ids);
        continue;
      }
      await j.choose_store();
    }
    await j.end_memories();
  }
}

async function 神雕侠侣(d, name, ins_id, material_quantity, duration) {
  var day, event_id, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_id = d.find("event_id=(\\d+)\">战斗\\(等级2\\)")))) {
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      }
      if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级2\\)")))) {
        await j.choose_adventure(day, event_id, [3]);
      }
      await j.choose_store();
    }
    await j.end_memories();
  }
}

async function 雪山藏魂(d, name, ins_id, material_quantity, duration) {
  var adventure_ids, day, event_id, event_ids, is_conversation, j;
  is_conversation = false;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if ((day === 4)) {
        if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级2\\)")))) {
          is_conversation = true;
          await j.choose_adventure(day, event_id, [2, 2]);
          continue;
        }
      }
      if (pyTruthy((event_ids = d.findall("event_id=(\\d+)\">战斗\\(等级2\\)")))) {
        if ((contains(pySet([2, 5]), day))) {
          event_id = event_ids[(-1)];
        } else {
          event_id = event_ids[0];
        }
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级2\\)")))) {
        if ((day === 1)) {
          adventure_ids = [1];
        } else if ((day === 6)) {
          if (pyTruthy(is_conversation)) {
            adventure_ids = [1];
          } else {
            adventure_ids = [2];
          }
        } else {
          adventure_ids = [];
        }
        await j.choose_adventure(day, event_id, adventure_ids);
      }
      await j.choose_store();
    }
    await j.end_memories();
  }
}

async function 桃花自古笑春风(d, name, ins_id, material_quantity, duration) {
  var adventure_ids, day, event_id, event_ids, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_ids = d.findall("event_id=(\\d+)\">战斗\\(等级2\\)")))) {
        event_id = event_ids[(-1)];
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级2\\)")))) {
        if ((contains(pySet([1, 7]), day))) {
          adventure_ids = [2, 2];
        } else if ((day === 5)) {
          adventure_ids = [2];
        } else {
          adventure_ids = [];
        }
        await j.choose_adventure(day, event_id, adventure_ids);
      }
    }
    await j.end_memories();
  }
}

async function 战乱襄阳(d, name, ins_id, material_quantity, duration) {
  var adventure_ids, day, event_id, event_ids, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_ids = d.findall("event_id=(\\d+)\">战斗\\(等级2\\)")))) {
        event_id = event_ids[(-1)];
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级2\\)")))) {
        if ((day === 4)) {
          adventure_ids = [1, 1, 1];
        } else {
          adventure_ids = [];
        }
        await j.choose_adventure(day, event_id, adventure_ids);
      }
    }
    await j.end_memories();
  }
}

async function 天涯浪子(d, name, ins_id, material_quantity, duration) {
  var adventure_ids, day, event_id, event_ids, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_ids = d.findall("event_id=(\\d+)\">战斗")))) {
        event_id = event_ids[(-1)];
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇")))) {
        if ((day === 1)) {
          adventure_ids = [1, 2];
        } else if ((day === 2)) {
          adventure_ids = [2, 2];
        } else if ((day === 3)) {
          adventure_ids = [3];
        } else if ((day === 4)) {
          adventure_ids = [2];
        } else if ((day === 5)) {
          adventure_ids = [2, 1];
        } else if ((day === 6)) {
          adventure_ids = [1];
        } else {
          adventure_ids = [];
        }
        await j.choose_adventure(day, event_id, adventure_ids);
      }
    }
    await j.end_memories();
  }
}

async function 全真古墓意难平(d, name, ins_id, material_quantity, duration) {
  var day, event_id, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_id = d.find("event_id=(\\d+)\">战斗\\(等级2\\)")))) {
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">战斗\\(等级1\\)")))) {
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if ((day === 1)) {
        await j.choose_adventure(day, "1", [2]);
      } else if ((day === 3)) {
        await j.choose_adventure(day, "1", [1]);
      } else if ((day === 7)) {
        await j.choose_adventure(day, "1", [2, 2]);
      } else if ((day === 2)) {
        if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级1\\)")))) {
          await j.choose_adventure(day, event_id, [3]);
        } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级2\\)")))) {
          await j.choose_adventure(day, event_id, [1]);
        } else {
          await j.choose_store();
        }
      } else if ((day === 5)) {
        if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级1\\)")))) {
          await j.choose_adventure(day, event_id, [2]);
        } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级2\\)")))) {
          await j.choose_adventure(day, event_id, [1]);
        } else {
          await j.choose_store();
        }
      } else if ((day === 6)) {
        if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级1\\)")))) {
          await j.choose_adventure(day, event_id, [2]);
        } else {
          await j.choose_store();
        }
      }
    }
    await j.end_memories();
  }
}

async function 南海有岛名侠客(d, name, ins_id, material_quantity, duration) {
  var adventure_ids, day, event_id, event_ids, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_ids = d.findall("event_id=(\\d+)\">战斗\\(等级2\\)")))) {
        event_id = event_ids[(-1)];
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级2\\)")))) {
        if ((contains(pySet([1, 5]), day))) {
          adventure_ids = [1];
        } else if ((contains(pySet([6, 8]), day))) {
          adventure_ids = [1, 2];
        } else {
          adventure_ids = [];
        }
        await j.choose_adventure(day, event_id, adventure_ids);
      }
    }
    await j.end_memories();
  }
}

async function 老鹅的圣诞冒险(d, name, ins_id, material_quantity, duration) {
  var adventure_ids, day, event_id, event_ids, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_ids = d.findall("event_id=(\\d+)\">战斗")))) {
        if ((day === 3)) {
          event_id = event_ids[1];
        } else {
          event_id = event_ids[0];
        }
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇")))) {
        if ((day === 1)) {
          adventure_ids = [1];
        } else if ((day === 2)) {
          adventure_ids = [3];
        } else if ((day === 4)) {
          if ((contains(d.html, "继续前行"))) {
            adventure_ids = [1, 1];
          } else if ((contains(d.html, "路线1"))) {
            adventure_ids = [1];
          } else if ((contains(d.html, "视而不见"))) {
            adventure_ids = [2];
          } else {
            adventure_ids = [];
          }
        } else if ((day === 5)) {
          adventure_ids = [2, 2];
        } else {
          adventure_ids = [];
        }
        await j.choose_adventure(day, event_id, adventure_ids);
      }
    }
    await j.end_memories();
  }
}

async function 世外桃源梦一场(d, name, ins_id, material_quantity, duration) {
  var adventure_ids, day, event_id, event_ids, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_ids = d.findall("event_id=(\\d+)\">战斗\\(等级2\\)")))) {
        if ((contains(pySet([2, 3]), day))) {
          event_id = event_ids[(-1)];
        } else {
          event_id = event_ids[0];
        }
        if (!pyTruthy(await j.choose_fight(day, event_id))) {
          await j.end_memories();
          return;
        }
      } else if (pyTruthy((event_id = d.find("event_id=(\\d+)\">奇遇\\(等级2\\)")))) {
        if ((day === 1)) {
          adventure_ids = [2, 2];
        } else if ((day === 6)) {
          adventure_ids = [1];
        } else {
          adventure_ids = [];
        }
        await j.choose_adventure(day, event_id, adventure_ids);
      }
    }
    await j.end_memories();
  }
}

async function 中原武林之危(d, name, ins_id, material_quantity, duration) {
  var day, event_id, event_ids, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_ids = d.findall("event_id=(\\d+)\">战斗")))) {
        event_id = event_ids[(-1)];
        if (pyTruthy(await j.choose_fight(day, event_id))) {
          continue;
        }
        await j.end_memories();
        return;
      }
    }
    await j.end_memories();
  }
}

async function 世界树轮回秘境(d, name, ins_id, material_quantity, duration) {
  var day, event_id, event_ids, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_ids = d.findall("event_id=(\\d+)\">战斗")))) {
        event_id = event_ids[(-1)];
        if (pyTruthy(await j.choose_fight(day, event_id))) {
          continue;
        }
        await j.end_memories();
        return;
      }
    }
    await j.end_memories();
  }
}

async function 技冠五绝(d, name, ins_id, material_quantity, duration) {
  var day, event_id, j;
  j = new JiangHuDream(d, name, ins_id);
  for (let _ of pyRange(material_quantity)) {
    if (!pyTruthy(await j.begin_success())) {
      break;
    }
    for (let day of pyRange(pyAdd(duration, 1))) {
      day = await j.next_day(day);
      if ((day === null)) {
        return;
      }
      if (pyTruthy((event_id = d.find("event_id=(\\d+)\">战斗")))) {
        if (pyTruthy(await j.choose_fight(day, event_id))) {
          continue;
        }
        await j.end_memories();
        return;
      }
    }
    await j.end_memories();
  }
}

async function 江湖长梦(d) {
  var config, copy_name, data_dict, day, duration, enabled, end_date, ins_data, ins_id, material_id, material_name, material_quantity, max_copies, month, name, year;
  await d.get("cmd=jianghudream");
  ins_data = d.findall("id=(\\d+)\">(.*?)<");
  if (!pyTruthy(ins_data)) {
    d.log("无法获取副本id");
    return;
  }
  config = d.config("江湖长梦");
  max_copies = pyInt(d.config("江湖长梦.单次最大副本次数"));
  for (let [name, data_dict] of pyItems(config)) {
    if ((name === "单次最大副本次数")) {
      continue;
    }
    enabled = data_dict["enabled"];
    if (!pyTruthy(enabled)) {
      continue;
    }
    material_name = data_dict["material_name"];
    material_id = data_dict["material_id"];
    for (let [ins_id, copy_name] of ins_data) {
      if ((name !== copy_name)) {
        continue;
      }
      await d.get(`cmd=jianghudream&op=showCopyInfo&id=${ins_id}`);
      duration = d.find("副本时长：(\\d+)");
      if ((duration === null)) {
        d.log(`${name} -> 获取副本时长失败`);
        break;
      }
      if ((!contains(d.html, "常规副本"))) {
        year = d.find("-(\\d+)年");
        month = d.find("-\\d+年(\\d+)月");
        day = d.find("-\\d+年\\d+月(\\d+)日");
        if (((year === null) || (month === null) || (day === null))) {
          d.log(`${name} -> 获取结束日期失败`);
          return;
        }
        end_date = DateTime.get_offset_date(pyAdd(2000, pyInt(year)), pyInt(month), pyInt(day));
        if ((DateTime.current_date() > end_date)) {
          d.log(`${name} -> 不在开启时间内`);
          continue;
        }
      }
      material_quantity = await c_get_material_quantity(d, material_id);
      if ((material_quantity === 0)) {
        d.log(`${name} -> ${material_name}不足`);
        continue;
      }
      if ((material_quantity > max_copies)) {
        d.log(`${name} -> 本次最多开启${max_copies}次，剩余留待下次`);
        material_quantity = max_copies;
      }
      await __globals[name](d, name, ins_id, material_quantity, pyInt(duration));
    }
  }
}

register("江湖长梦", 江湖长梦);

async function 深渊之潮(d) {
  await c_帮派巡礼(d);
  await c_深渊秘境(d);
}

register("深渊之潮", 深渊之潮);

async function 侠客岛(d) {
  var p;
  await d.get("cmd=knight_island&op=viewmissionindex");
  for (let p of d.findall("getmissionreward&amp;pos=(\\d+)")) {
    await d.get(`cmd=knight_island&op=getmissionreward&pos=${p}`);
    d.log(d.find("斗豆）<br />(.*?)<br />"));
  }
}

register("侠客岛", 侠客岛);

async function 龙凰之境(d) {
  await c_龙凰论武(d);
}

register("龙凰之境", 龙凰之境);

async function 背包(d) {
  var _id, data, material_name, max_pages, max_uses, p, quantity, use, used_count;
  use = d.config("背包.使用");
  max_pages = pyInt(d.config("背包.最大扫描页数"));
  max_uses = pyInt(d.config("背包.最大使用次数"));
  data = [];
  for (let p of pyRange(1, pyAdd(max_pages, 1))) {
    d.log(`第 ${p} 页`);
    await d.get(`cmd=store&store_type=0&page=${p}`);
    data = pyAdd(data, d.findall("id=(\\d+)\">(.*?)</a>数量：(\\d+)"));
    if ((!contains(d.html, "下页"))) {
      break;
    }
  }
  if ((contains(d.html, "下页"))) {
    d.log(`达到最大扫描页数 ${max_pages}，本次停止继续翻页`);
  }
  used_count = 0;
  for (let [_id, material_name, quantity] of data) {
    if (!pyTruthy(pyAny(use, (u) => (contains(material_name, u))))) {
      continue;
    }
    for (let _ of pyRange(pyInt(quantity))) {
      if ((used_count >= max_uses)) {
        d.log(`达到最大使用次数 ${max_uses}，本次停止使用道具`);
        return;
      }
      await d.get(`cmd=use&id=${_id}`);
      used_count = pyAdd(used_count, 1);
      if (((contains(d.html, "您使用了")) || (contains(d.html, "你打开")))) {
        d.log(d.find());
        continue;
      }
      d.log(`${material_name}（${_id}） -> ${d.find("】</p><p>(.*?)<")}`);
      break;
    }
  }
}

register("背包", 背包);

async function 镶嵌(d) {
  var _id, data_1, data_2, e, material_name, need, p, possess;
  if ((DateTime.week() !== 4)) {
    return;
  }
  for (let p of pyRange(1, 8)) {
    await d.get(`cmd=upgradepearl&type=1&pearl_type=${p}`);
    data_1 = d.findall("<br />.*?:(\\d+), (\\d+).*?exchangetype=(\\d+)");
    data_2 = d.findall("><br />(.*?):(\\d+), (\\d+).*?pearl_id=(\\d+)");
    for (let [need, possess, e] of data_1) {
      for (let _ of pyRange(Math.floor(pyInt(possess) / pyInt(need)))) {
        await d.get(`cmd=upgradepearl&type=6&exchangetype=${e}`);
        d.log(d.find("魂珠升级</p><p>(.*?)</p>"));
      }
    }
    for (let [material_name, need, possess, _id] of pySlice(data_2, null, 3)) {
      for (let _ of pyRange(Math.floor(pyInt(possess) / pyInt(need)))) {
        await d.get(`cmd=upgradepearl&type=3&pearl_id=${_id}&pearl_type=${p}`);
        d.log(`${material_name} -> ${d.find("魂珠升级</p><p>(.*?)<")}`);
      }
    }
  }
}

register("镶嵌", 镶嵌);

async function 普通合成(d) {
  var _id, data, need, p, possess;
  for (let p of pyRange(1, 20)) {
    await d.get(`cmd=weapongod&sub=12&stone_type=0&quality=0&page=${p}`);
    data = d.findall("拥有：(\\d+)/(\\d+).*?stone_id=(\\d+)");
    for (let [possess, need, _id] of data) {
      for (let _ of pyRange(Math.floor(pyInt(possess) / pyInt(need)))) {
        await d.get(`cmd=weapongod&sub=13&stone_id=${_id}`);
        d.log(d.find("背包<br /></p>(.*?)<"));
      }
    }
    if ((!contains(d.html, "下一页"))) {
      break;
    }
  }
}

async function 符石分解(d) {
  var _id, data, material_name, num, p;
  data = [];
  for (let p of pyRange(1, 10)) {
    d.log(`查找符石分解第 ${p} 页`);
    await d.get(`cmd=weapongod&sub=9&stone_type=0&page=${p}`);
    data = pyAdd(data, d.findall(">\\d+. (.*?) \\(数量:(\\d+).*?stone_id=(\\d+)"));
    if ((!contains(d.html, "下一页"))) {
      break;
    }
  }
  for (let [material_name, num, _id] of data) {
    if ((pyTruthy(material_name.endsWith("I")) && !pyTruthy(material_name.endsWith("II")) && !pyTruthy(material_name.endsWith("III")))) {
      await d.get(`cmd=weapongod&sub=11&stone_id=${_id}&num=${num}&i_p_w=num%7C`);
      d.log(`${material_name} -> ${d.find("背包</a><br /></p>(.*?)<")}`);
    } else if ((pyTruthy(material_name.endsWith("II")) && !pyTruthy(material_name.endsWith("III")))) {
      await d.get(`cmd=weapongod&sub=11&stone_id=${_id}&num=${num}&i_p_w=num%7C`);
      d.log(`${material_name} -> ${d.find("背包</a><br /></p>(.*?)<")}`);
    }
  }
}

async function 符石打造(d) {
  var count, quotient, remainder;
  await d.get("cmd=weapongod&sub=7");
  count = d.find("符石水晶：(\\d+)");
  if ((count === null)) {
    d.log("获取符石水晶数量失败");
    return;
  }
  [quotient, remainder] = pyDivmod(pyInt(count), 60);
  for (let _ of pyRange(quotient)) {
    await d.get("cmd=weapongod&sub=8&produce_type=1&times=10");
    d.log(d.find("背包</a><br /></p>(.*?)<"));
  }
  for (let _ of pyRange(Math.floor(remainder / 6))) {
    await d.get("cmd=weapongod&sub=8&produce_type=1&times=1");
    d.log(d.find("背包</a><br /></p>(.*?)<"));
  }
}

async function 神匠坊(d) {
  if ((DateTime.week() !== 4)) {
    return;
  }
  await 普通合成(d);
  await 符石分解(d);
  await 符石打造(d);
}

register("神匠坊", 神匠坊);

async function 每日宝箱(d) {
  var need, possess, t;
  if ((DateTime.week() !== 4)) {
    return;
  }
  await d.get("cmd=dailychest");
  for (let [t, possess, need] of d.findall("type=(\\d+)\">打开.*?(\\d+)/(\\d+)")) {
    for (let _ of pyRange(pyMin(10, null))) {
      await d.get(`cmd=dailychest&op=open&type=${t}`);
      d.log(d.find("说明</a><br />(.*?)<"));
      if ((contains(d.html, "今日开宝箱次数已达上限"))) {
        break;
      }
    }
  }
}

register("每日宝箱", 每日宝箱);

async function 猜单双(d) {
  var value;
  await d.get("cmd=oddeven");
  for (let _ of pyRange(5)) {
    value = d.findall("value=(\\d+)\">.*?数");
    if (!pyTruthy(value)) {
      d.log("猜单双已经结束");
      break;
    }
    value = randomChoice(value);
    await d.get(`cmd=oddeven&value=${value}`);
    d.log(d.find());
  }
}

register("猜单双", 猜单双);

async function 煮元宵(d) {
  var maturity;
  await d.get("cmd=yuanxiao2014");
  for (let _ of pyRange(4)) {
    await d.get("cmd=yuanxiao2014&op=1");
    if ((contains(d.html, "领取烹饪次数"))) {
      d.log("没有烹饪次数了");
      break;
    }
    for (let _ of pyRange(20)) {
      maturity = d.find("当前元宵成熟度：(\\d+)");
      if ((maturity === null)) {
        d.log("获取元宵成熟度失败");
        return;
      }
      if ((pyInt(maturity) < 96)) {
        await d.get("cmd=yuanxiao2014&op=2");
        continue;
      }
      await d.get("cmd=yuanxiao2014&op=3");
      d.log(d.find("活动规则</a><br /><br />(.*?)。"));
      break;
    }
  }
}

register("煮元宵", 煮元宵);

async function 元宵节(d) {
  await d.get("cmd=newAct&subtype=101&op=1");
  d.log(d.find("】</p>(.*?)<br />"));
  await d.get("cmd=newAct&subtype=101&op=2&index=0");
  d.log(d.find("】</p>(.*?)<br />"));
}

register("元宵节", 元宵节);

async function 刮刮卡(d) {
  var _id;
  for (let _id of pyRange(3)) {
    await d.get(`cmd=newAct&subtype=148&op=2&id=${_id}`);
    d.log(d.find("奖池预览</a><br /><br />(.*?)<br />"));
  }
  for (let _ of pyRange(20)) {
    await d.get("cmd=newAct&subtype=148&op=1");
    d.log(d.find("奖池预览</a><br /><br />(.*?)<br />"));
    if ((contains(d.html, "您没有刮刮卡了"))) {
      break;
    } else if ((contains(d.html, "不在刮奖时间不能刮奖"))) {
      break;
    }
  }
}

register("刮刮卡", 刮刮卡);

async function 娃娃机(d) {
  await d.get("cmd=newAct&subtype=124&op=0");
  if ((!contains(d.html, "免费次数：1/1"))) {
    d.log("没有免费抓取次数");
    return;
  }
  await d.get("cmd=newAct&subtype=124&op=1");
  d.log(d.find());
}

register("娃娃机", 娃娃机);

async function 吉利兑(d) {
  var _id, day, end_date, exchange_config, item, material_name, month, quantity;
  await d.get("cmd=geelyexchange");
  for (let _id of d.findall("id=(\\d+)\">领取</a>")) {
    await d.get(`cmd=geelyexchange&op=GetTaskReward&id=${_id}`);
    d.log(d.find("】<br /><br />(.*?)<br /><br />"));
  }
  month = d.find("至(\\d+)月");
  day = d.find("至\\d+月(\\d+)日");
  if (((month === null) || (day === null))) {
    d.log("获取结束日期失败");
    return;
  }
  end_date = DateTime.get_offset_date(DateTime.year(), pyInt(month), pyInt(day));
  if ((DateTime.current_date() !== end_date)) {
    return;
  }
  exchange_config = d.config("吉利兑.exchange");
  for (let [_id, item] of pyItems(exchange_config)) {
    material_name = item["material_name"];
    quantity = item["quantity"];
    if ((quantity <= 0)) {
      continue;
    }
    for (let _ of pyRange(quantity)) {
      await d.get(`cmd=geelyexchange&op=ExchangeProps&id=${_id}`);
      d.log(`${material_name}*1 -> ${d.find("】<br /><br />(.*?)<br />")}`);
      if ((contains(d.html, "你的精魄不足，快去完成任务吧~"))) {
        break;
      } else if ((contains(d.html, "该物品已达兑换上限~"))) {
        break;
      }
    }
  }
}

register("吉利兑", 吉利兑);

async function 激运牌(d) {
  var _id, count;
  for (let _id of [0, 1]) {
    await d.get(`cmd=realgoods&op=getTaskReward&id=${_id}`);
    d.log(d.find("<br /><br />(.*?)<br />"));
  }
  count = d.find("我的激运牌：(\\d+)");
  if ((count === null)) {
    d.log("获取激运牌次数失败");
    return;
  }
  for (let _ of pyRange(pyInt(count))) {
    await d.get("cmd=realgoods&op=lotteryDraw");
    d.log(d.find("<br /><br />(.*?)<br />"));
  }
}

register("激运牌", 激运牌);

async function 回忆录(d) {
  var _id;
  if ((DateTime.week() !== 4)) {
    return;
  }
  for (let _id of pyRange(1, 11)) {
    await d.get(`cmd=newAct&subtype=171&op=3&id=${_id}`);
    d.log(d.find("6点<br />(.*?)<br />"));
  }
}

register("回忆录", 回忆录);

async function 愚人节(d) {
  var _id;
  for (let _ of pyRange(5)) {
    await d.get("cmd=foolsday&gb_id=5");
    d.log(d.find("\\d+<br /><br />(.*?)<"));
    if ((!contains(d.html, "提升20幸运值"))) {
      break;
    }
  }
  for (let _id of d.findall("gb_id=(\\d+)\">拆开")) {
    await d.get(`cmd=foolsday&gb_id=${_id}`);
    if ((contains(d.html, "确认"))) {
      d.log("今日幸运度较低，是否确认拆开礼包？");
      await d.get("cmd=foolsday&gb_id=1");
    }
    d.log(d.find("\\d+<br /><br />(.*?)<"));
  }
}

register("愚人节", 愚人节);

async function 疯狂许愿(d, link_text) {
  var config, s, t;
  await d.get("cmd=newAct&subtype=130");
  if ((contains(d.html, "取消返回"))) {
    await d.get("cmd=newAct&subtype=130&op=6");
  }
  if ((!contains(d.html, "op=2"))) {
    d.log("你已经领取过了", link_text);
    return;
  }
  config = d.config(`${link_text}.id`);
  if ((config === null)) {
    d.log(`你没有设置${link_text}`, link_text);
    return;
  }
  [t, s] = d.findall("type=(\\d+)&sub_type=(\\d+)", config)[0];
  await d.get(`cmd=newAct&subtype=130&op=2&type=${t}`);
  await d.get(`cmd=newAct&subtype=130&op=3&type=${t}&sub_type=${s}`);
  d.log(d.find("】</p>(.*?)<"), link_text);
}

async function 儿童节(d) {
  await 疯狂许愿(d, "儿童节");
}

register("儿童节", 儿童节);

async function 开学季(d) {
  await 疯狂许愿(d, "开学季");
}

register("开学季", 开学季);

async function 大笨钟(d) {
  await c_大笨钟(d);
}

register("大笨钟", 大笨钟);

async function 幸运金蛋(d) {
  await c_幸运金蛋(d);
}

register("幸运金蛋", 幸运金蛋);

async function 客栈同福(d) {
  await c_客栈同福(d);
}

register("客栈同福", 客栈同福);

async function 斗神塔(d, link_text) {
  var count, second;
  count = d.config(`${link_text}.斗神塔.count`);
  if ((count <= 0)) {
    d.log(`斗神塔 -> 你设置自动挑战次数为${count}`);
    return;
  }
  second = await c_get_doushenta_cd(d);
  for (let _ of pyRange(count)) {
    await d.get("cmd=towerfight&type=11");
    d.log(`斗神塔 -> ${d.find()}`);
    if ((contains(d.html, "结束挑战"))) {
      await sleep(second);
      await d.get("cmd=towerfight&type=7");
      d.log(`斗神塔 -> ${d.find()}`);
    } else {
      break;
    }
  }
}

async function 节日福利(d) {
  await 斗神塔(d, "节日福利");
}

register("节日福利", 节日福利);

async function 双旦福利(d) {
  await 斗神塔(d, "双旦福利");
}

register("双旦福利", 双旦福利);

async function 金秋福利(d) {
  await 斗神塔(d, "金秋福利");
}

register("金秋福利", 金秋福利);

async function 春节福利(d) {
  await 斗神塔(d, "春节福利");
}

register("春节福利", 春节福利);

async function 多倍福利(d) {
  await 斗神塔(d, "多倍福利");
}

register("多倍福利", 多倍福利);

async function 新春拜年(d) {
  await d.get("cmd=newAct&subtype=147");
  if ((!contains(d.html, "op=3"))) {
    d.log("没有礼物收取");
    return;
  }
  await d.get("cmd=newAct&subtype=147&op=3");
  d.log(d.find("祝您：.*?<br /><br />(.*?)<br />"));
}

register("新春拜年", 新春拜年);

async function 神魔转盘(d) {
  await d.get("cmd=newAct&subtype=88&op=0");
  if ((!contains(d.html, "免费抽奖一次"))) {
    d.log("没有免费抽奖次数了");
    return;
  }
  await d.get("cmd=newAct&subtype=88&op=1");
  d.log(d.find());
}

register("神魔转盘", 神魔转盘);

async function 乐斗驿站(d) {
  await d.get("cmd=newAct&subtype=167&op=0");
  if ((!contains(d.html, "cmd=newAct&amp;subtype=167&amp;op=2"))) {
    d.log("没有免费领取");
    return;
  }
  await d.get("cmd=newAct&subtype=167&op=2");
  d.log(d.find());
}

register("乐斗驿站", 乐斗驿站);

async function 幸运转盘(d) {
  await d.get("cmd=newAct&subtype=57&op=roll");
  d.log(d.find("0<br /><br />(.*?)<br />"));
}

register("幸运转盘", 幸运转盘);

async function 冰雪企缘(d) {
  var _id, gift;
  await d.get("cmd=newAct&subtype=158&op=0");
  gift = d.findall("gift_type=(\\d+)");
  if (!pyTruthy(gift)) {
    d.log("没有礼包领取");
    return;
  }
  for (let _id of gift) {
    await d.get(`cmd=newAct&subtype=158&op=2&gift_type=${_id}`);
    d.log(d.find());
  }
}

register("冰雪企缘", 冰雪企缘);

async function 甜蜜夫妻(d) {
  var f;
  await d.get("cmd=newAct&subtype=129");
  for (let f of d.findall("flag=(\\d+)")) {
    await d.get(`cmd=newAct&subtype=129&op=1&flag=${f}`);
    d.log(d.find("】</p>(.*?)<br />"));
  }
}

register("甜蜜夫妻", 甜蜜夫妻);

async function 乐斗菜单(d) {
  var gift;
  await d.get("cmd=menuact");
  if (pyTruthy((gift = d.find("套餐.*?gift=(\\d+).*?点单</a>")))) {
    await d.get(`cmd=menuact&sub=1&gift=${gift}`);
    d.log(d.find("哦！<br /></p>(.*?)<br />"));
  }
}

register("乐斗菜单", 乐斗菜单);

async function 周周礼包(d) {
  var _id, gift_ids;
  await d.get("cmd=weekgiftbag&sub=0");
  gift_ids = d.findall("cmd=weekgiftbag&amp;sub=1&amp;id=(\\d+).*?>领取");
  if (!pyTruthy(gift_ids)) {
    d.log("没有礼包领取");
    return;
  }
  for (let _id of gift_ids) {
    await d.get(`cmd=weekgiftbag&sub=1&id=${_id}`);
    d.log(d.find());
  }
}

register("周周礼包", 周周礼包);

async function 登录有礼(d) {
  var g;
  await d.get("cmd=newAct&subtype=56");
  if (pyTruthy((g = d.find("gift_type=1.*?gift_index=(\\d+)")))) {
    await d.get(`cmd=newAct&subtype=56&op=draw&gift_type=1&gift_index=${g}`);
    d.log(d.find());
  }
  if (pyTruthy((g = d.find("gift_type=2.*?gift_index=(\\d+)")))) {
    await d.get(`cmd=newAct&subtype=56&op=draw&gift_type=2&gift_index=${g}`);
    d.log(d.find());
  }
}

register("登录有礼", 登录有礼);

async function 活跃礼包(d) {
  var p;
  for (let p of ["1", "2"]) {
    await d.get(`cmd=newAct&subtype=94&op=${p}`);
    d.log(d.find("】.*?<br />(.*?)<br />"));
  }
}

register("活跃礼包", 活跃礼包);

async function 清明上香(d) {
  var _id, count;
  await d.get("cmd=newAct&subtype=142");
  for (let [_id, count] of d.findall("id=(\\d+).*?（(\\d+)）")) {
    for (let _ of pyRange(pyInt(count))) {
      await d.get(`cmd=newAct&subtype=142&op=1&id=${_id}`);
      d.log(d.find());
    }
  }
}

register("清明上香", 清明上香);

async function 徽章战令(d) {
  await d.get("cmd=badge&op=1");
  d.log(d.find());
}

register("徽章战令", 徽章战令);

async function 生肖福卡_好友赠卡(d) {
  var card_id, name, qq;
  await d.get("cmd=newAct&subtype=174&op=4");
  for (let [name, qq, card_id] of d.findall("送您(.*?)\\*.*?oppuin=(\\d+).*?id=(\\d+)")) {
    await d.get(`cmd=newAct&subtype=174&op=6&oppuin=${qq}&card_id=${card_id}`);
    d.log(d.find());
  }
}

async function 生肖福卡_分享福卡(d) {
  var _id, data, max_number, pattern, qq;
  qq = d.config("生肖福卡.QQ");
  if ((qq === null)) {
    return;
  }
  await d.get("cmd=newAct&subtype=174");
  pattern = "[子丑寅卯辰巳午未申酉戌亥][鼠牛虎兔龙蛇马羊猴鸡狗猪]";
  data = d.findall(`(${pattern})\\s+(\\d+).*?id=(\\d+)`);
  [_, max_number, _id] = pyMax(data, (x) => pyInt(x[1]));
  if ((pyInt(max_number) >= 2)) {
    await d.get(`cmd=newAct&subtype=174&op=5&oppuin=${qq}&card_id=${_id}&confirm=1`);
    d.log(d.find("~<br /><br />(.*?)<br />"));
  }
}

async function 生肖福卡_领取福卡(d) {
  var _id;
  await d.get("cmd=newAct&subtype=174");
  for (let _id of d.findall("task_id=(\\d+)")) {
    await d.get(`cmd=newAct&subtype=174&op=7&task_id=${_id}`);
    d.log(d.find("~<br /><br />(.*?)<br />"));
  }
}

async function 生肖福卡_合卡(d) {
  var day, month;
  await d.get("cmd=newAct&subtype=174");
  [month, day] = d.findall("合卡时间：.*?至(\\d+)月(\\d+)日")[0];
  if (((DateTime.month() === pyInt(month)) && (DateTime.day() === pyInt(day)))) {
    return;
  }
  await d.get("cmd=newAct&subtype=174&op=8");
  d.log(d.find("。<br /><br />(.*?)<br />"));
}

async function 生肖福卡_抽奖(d) {
  var _id, data, day, min_number, month, numbers;
  await d.get("cmd=newAct&subtype=174");
  [month, day] = d.findall("兑奖时间：(\\d+)月(\\d+)日")[0];
  if (!pyTruthy(((DateTime.month() === pyInt(month)) && (DateTime.day() >= pyInt(day))))) {
    return;
  }
  await d.get("cmd=newAct&subtype=174&op=9");
  d.log(d.find("。<br /><br />(.*?)<br />"));
  await d.get("cmd=newAct&subtype=174&op=2");
  for (let [_id, data] of d.findall("id=(\\d+).*?<br />(.*?)<br />")) {
    numbers = d.findall("\\d+", data);
    min_number = pyMin(numbers, (x) => pyInt(x));
    for (let _ of pyRange(pyInt(min_number))) {
      await d.get(`cmd=newAct&subtype=174&op=10&id=${_id}&confirm=1`);
      if ((contains(d.html, "您还未合成周年福卡"))) {
        await d.get(`cmd=newAct&subtype=174&op=10&id=${_id}`);
      }
      d.log(d.find("幸运抽奖<br /><br />(.*?)<br />"));
    }
  }
}

async function 生肖福卡(d) {
  await 生肖福卡_好友赠卡(d);
  await 生肖福卡_分享福卡(d);
  await 生肖福卡_领取福卡(d);
  if ((DateTime.week() !== 4)) {
    return;
  }
  await 生肖福卡_合卡(d);
  await 生肖福卡_抽奖(d);
}

register("生肖福卡", 生肖福卡);

async function 长安盛会(d) {
  var _id, count;
  await d.get("cmd=newAct&subtype=118&op=2&select_id=5089");
  for (let _id of d.findall("op=1&amp;id=(\\d+)")) {
    if ((contains(["1", "2"], _id))) {
      await d.get(`cmd=newAct&subtype=118&op=1&id=${_id}`);
      d.log(d.find());
    } else {
      count = d.find("剩余转动次数：(\\d+)");
      if ((count === null)) {
        d.log("获取剩余转动次数失败");
        return;
      }
      for (let _ of pyRange(pyInt(count))) {
        await d.get(`cmd=newAct&subtype=118&op=1&id=${_id}`);
        d.log(d.find());
      }
    }
  }
}

register("长安盛会", 长安盛会);

async function 深渊秘宝(d) {
  var t, t_list;
  await d.get("cmd=newAct&subtype=175");
  t_list = d.findall("type=(\\d+)&amp;times=1\">免费抽奖");
  if (!pyTruthy(t_list)) {
    d.log("没有免费抽奖次数了");
    return;
  }
  for (let t of t_list) {
    await d.get(`cmd=newAct&subtype=175&op=1&type=${t}&times=1`);
    d.log(d.find());
  }
}

register("深渊秘宝", 深渊秘宝);

async function 中秋礼盒(d) {
  var _id;
  await d.get("cmd=midautumngiftbag&sub=0");
  for (let _id of d.findall("amp;id=(\\d+)")) {
    await d.get(`cmd=midautumngiftbag&sub=1&id=${_id}`);
    d.log(d.find());
    if ((contains(d.html, "已领取完该系列任务所有奖励"))) {
      continue;
    }
  }
}

register("中秋礼盒", 中秋礼盒);

async function 双节签到(d) {
  var day, end_date, month;
  await d.get("cmd=newAct&subtype=144&op=1");
  d.log(d.find());
  month = d.find("至(\\d+)月");
  day = d.find("至\\d+月(\\d+)日");
  if (((month === null) || (day === null))) {
    d.log("获取结束日期失败");
    return;
  }
  end_date = DateTime.get_offset_date(DateTime.year(), pyInt(month), pyInt(day));
  if ((DateTime.current_date() === end_date)) {
    await d.get("cmd=newAct&subtype=144&op=3");
    d.log(d.find());
  }
}

register("双节签到", 双节签到);

async function 斗境探秘(d) {
  var _id;
  await d.get("cmd=newAct&subtype=177");
  for (let _id of d.findall("id=(\\d+)&amp;type=2")) {
    await d.get(`cmd=newAct&subtype=177&op=2&id=${_id}&type=2`);
    d.log(d.find("】<br /><br />(.*?)<br />"));
  }
  for (let _id of d.findall("id=(\\d+)&amp;type=1")) {
    await d.get(`cmd=newAct&subtype=177&op=2&id=${_id}&type=1`);
    d.log(d.find("】<br /><br />(.*?)<br />"));
  }
}

register("斗境探秘", 斗境探秘);

async function 春联大赛(d) {
  var _id, couplets, index, index_A, index_B, index_C, options_A, options_B, options_C, options_dict, shang_lian, xia_lian;
  await d.get("cmd=newAct&subtype=146&op=1");
  if ((contains(d.html, "您的活跃度不足"))) {
    d.log("您的活跃度不足50");
    return;
  }
  couplets = d.config("春联大赛");
  for (let _ of pyRange(3)) {
    if ((contains(d.html, "今日答题已结束"))) {
      d.log("今日答题已结束");
      break;
    }
    shang_lian = d.find("上联：([^ &]*)");
    d.log(`上联: ${shang_lian}`);
    [options_A, index_A] = d.findall("<br />A.(.*?)<.*?index=(\\d+)")[0];
    [options_B, index_B] = d.findall("<br />B.(.*?)<.*?index=(\\d+)")[0];
    [options_C, index_C] = d.findall("<br />C.(.*?)<.*?index=(\\d+)")[0];
    options_dict = ({[options_A]: index_A, [options_B]: index_B, [options_C]: index_C});
    if (pyTruthy((xia_lian = pyGet(couplets, shang_lian, null)))) {
      index = options_dict[xia_lian];
      await d.get(`cmd=newAct&subtype=146&op=3&index=${index}`);
      d.log(`下联: ${xia_lian}`);
      await d.get("cmd=newAct&subtype=146&op=2");
      d.log(d.find());
    } else {
      d.log("题库没有找到对联，请在配置文件更新题库");
      break;
    }
  }
  for (let _id of d.findall("id=(\\d+)\">领取")) {
    await d.get(`cmd=newAct&subtype=146&op=4&id=${_id}`);
    d.log(d.find());
  }
}

register("春联大赛", 春联大赛);

async function 预热礼包(d) {
  await d.get("cmd=newAct&subtype=117&op=1");
  d.log(d.find("<br /><br />(.*?)<"));
}

register("预热礼包", 预热礼包);

async function 豪侠出世(d) {
  var _id;
  await d.get("cmd=knightdraw&op=view&sub=signin&ty=free");
  for (let _id of d.findall("giftId=(\\d+)")) {
    await d.get(`cmd=knightdraw&op=reqreward&sub=signin&ty=free&giftId=${_id}`);
    d.log(d.find("活动规则</a><br />(.*?)<br />"));
  }
}

register("豪侠出世", 豪侠出世);

async function 乐斗游记(d) {
  var _id, count, quotient, remainder;
  await d.get("cmd=newAct&subtype=176");
  for (let _id of d.findall("task_id=(\\d+)")) {
    await d.get(`cmd=newAct&subtype=176&op=1&task_id=${_id}`);
    d.log(d.find("积分。<br /><br />(.*?)<br />"));
  }
  await d.get("cmd=newAct&subtype=176&op=5");
  d.log(d.find("积分。<br /><br />(.*?)<br />"));
  count = d.find("溢出积分：(\\d+)");
  if ((count === null)) {
    d.log("获取溢出积分失败");
    return;
  }
  [quotient, remainder] = pyDivmod(pyInt(count), 10);
  for (let _ of pyRange(quotient)) {
    await d.get("cmd=newAct&subtype=176&op=2&num=10");
    d.log(d.find("积分。<br /><br />(.*?)<br />"));
  }
  for (let _ of pyRange(remainder)) {
    await d.get("cmd=newAct&subtype=176&op=2&num=1");
    d.log(d.find("积分。<br /><br />(.*?)<br />"));
  }
}

register("乐斗游记", 乐斗游记);

async function 喜从天降(d) {
  var count;
  await d.get("cmd=newAct&subtype=137");
  count = d.find("剩余燃放次数：(\\d+)");
  if ((count === null)) {
    d.log("获取燃放次数失败");
    return;
  }
  for (let _ of pyRange(pyInt(count))) {
    await d.get("cmd=newAct&subtype=137&op=1");
    d.log(d.find());
  }
}

register("喜从天降", 喜从天降);

async function 微信兑换(d) {
  var code;
  if ((DateTime.week() !== 4)) {
    return;
  }
  code = d.config("微信兑换.兑换码");
  await d.get(`cmd=weixin&cdkey=${code}&sub=2&zapp_sid=&style=0&channel=0&i_p_w=cdkey|`);
  d.log(d.find());
}

register("微信兑换", 微信兑换);

async function 浩劫宝箱(d) {
  var t1, t2;
  await d.get("cmd=index&style=1");
  t1 = d.find("subtype=(\\d+)\">浩劫宝箱");
  await d.get(`cmd=newAct&subtype=${t1}`);
  if (pyTruthy((t2 = d.find("subtype=(\\d+)")))) {
    await d.get(`cmd=newAct&subtype=${t2}`);
    d.log(d.find());
  }
}

register("浩劫宝箱", 浩劫宝箱);

async function 端午有礼(d) {
  if ((DateTime.week() !== 4)) {
    return;
  }
  for (let _ of pyRange(2)) {
    await d.get("cmd=newAct&subtype=121&op=1&index=3");
    d.log(d.find("】<br /><br />(.*?)<br />"));
    if ((contains(d.html, "您的端午香粽不足"))) {
      break;
    }
  }
  await d.get("cmd=newAct&subtype=121&op=1&index=2");
  d.log(d.find("】<br /><br />(.*?)<br />"));
}

register("端午有礼", 端午有礼);

async function 圣诞有礼(d) {
  var _id, i;
  await d.get("cmd=newAct&subtype=145");
  for (let _id of d.findall("task_id=(\\d+)")) {
    await d.get(`cmd=newAct&subtype=145&op=1&task_id=${_id}`);
    d.log(d.find());
  }
  for (let i of d.findall("index=(\\d+)")) {
    await d.get(`cmd=newAct&subtype=145&op=2&index=${i}`);
    d.log(d.find());
  }
}

register("圣诞有礼", 圣诞有礼);

async function 新春礼包(d) {
  var _id;
  for (let _id of [280, 281, 282]) {
    await d.get(`cmd=xinChunGift&subtype=2&giftid=${_id}`);
    d.log(d.find());
  }
}

register("新春礼包", 新春礼包);

async function 登录商店(d) {
  var t;
  if ((DateTime.week() !== 4)) {
    return;
  }
  t = d.config("登录商店.id");
  if ((t === null)) {
    d.log("你没有配置兑换物品id");
    return;
  }
  for (let _ of pyRange(5)) {
    await d.get(`cmd=newAct&op=exchange&subtype=52&type=${t}&times=5`);
    d.log(d.find("<br /><br />(.*?)<br /><br />"));
  }
  for (let _ of pyRange(3)) {
    await d.get(`cmd=newAct&op=exchange&subtype=52&type=${t}&times=1`);
    d.log(d.find("<br /><br />(.*?)<br /><br />"));
  }
}

register("登录商店", 登录商店);

async function 盛世巡礼(d) {
  var _id, s;
  if ((DateTime.week() !== 4)) {
    return;
  }
  for (let s of pyRange(1, 8)) {
    await d.get(`cmd=newAct&subtype=150&op=2&sceneId=${s}`);
    if ((contains(d.html, "他已经给过你礼物了"))) {
      d.log(`地点${s}礼物已领取`);
    } else if (((s === 7) && (!contains(d.html, "点击继续")))) {
      d.log(`地点${s}礼物已领取`);
    } else if (pyTruthy((_id = d.find("itemId=(\\d+)")))) {
      await d.get(`cmd=newAct&subtype=150&op=5&itemId=${_id}`);
      d.log(d.find("礼物<br />(.*?)<br />"));
    }
  }
}

register("盛世巡礼", 盛世巡礼);

async function 五一礼包(d) {
  var _id;
  for (let _id of pyRange(3)) {
    await d.get(`cmd=newAct&subtype=113&op=1&id=${_id}`);
    d.log(d.find("】<br /><br />(.*?)<"));
  }
}

register("5.1礼包", 五一礼包);

async function 五一预订(d) {
  var _id;
  await d.get("cmd=lokireservation");
  if (pyTruthy((_id = d.find("idx=(\\d+)")))) {
    await d.get(`cmd=lokireservation&op=draw&idx=${_id}`);
    d.log(d.find("<br /><br />(.*?)<"));
  }
}

register("五一预订", 五一预订);

async function 好礼提升(d) {
  await d.get("cmd=newAct&subtype=43&op=get");
  d.log(d.find());
}

register("好礼提升", 好礼提升);

async function 周年祝福(d) {
  var day;
  for (let day of pyRange(1, 8)) {
    await d.get(`cmd=newAct&subtype=165&op=3&day=${day}`);
    d.log(d.find());
  }
}

register("周年祝福", 周年祝福);

async function 周年预热(d) {
  await d.get("cmd=newAct&subtype=117&op=0");
  if ((contains(d.html, "op=1"))) {
    await d.get("cmd=newAct&subtype=117&op=1");
    d.log(d.find("<br /><br />(.*?)<"));
  }
}

register("周年预热", 周年预热);

async function 年兽大作战(d) {
  var _id, choose_count, choose_ids, name, t;
  await d.get("cmd=newAct&subtype=170&op=0");
  if ((contains(d.html, "等级不够"))) {
    d.log("等级不够，还未开启年兽大作战哦！");
    return;
  }
  if (pyTruthy((choose_count = pyCount(d.html, "暂未选择")))) {
    choose_ids = [];
    for (let t of pyRange(5)) {
      await d.get(`cmd=newAct&subtype=170&op=4&type=${t}`);
      choose_ids = pyAdd(choose_ids, d.findall("id=(\\d+)\">选择"));
      if ((pyLen(choose_ids) >= choose_count)) {
        break;
      }
    }
    if ((pyLen(choose_ids) < choose_count)) {
      d.log("自选武技库数量不够补位");
      return;
    }
    for (let _id of pySlice(choose_ids, null, choose_count)) {
      await d.get(`cmd=newAct&subtype=170&op=7&id=${_id}`);
      name = d.find(`id=${_id}">(.*?)<`);
      d.log(`${name}：${d.find()}`);
    }
  }
  if ((contains(d.html, "剩余免费随机次数：1"))) {
    await d.get("cmd=newAct&subtype=170&op=6");
    d.log(d.find());
  }
  for (let _ of pyRange(3)) {
    await d.get("cmd=newAct&subtype=170&op=8");
    d.log(d.find());
    await sleep(0.2);
  }
}

register("年兽大作战", 年兽大作战);

async function 新春登录礼(d) {
  var day, days;
  await d.get("cmd=newAct&subtype=99&op=0");
  days = d.findall("day=(\\d+)");
  if (!pyTruthy(days)) {
    d.log("没有礼包领取");
    return;
  }
  for (let day of days) {
    await d.get(`cmd=newAct&subtype=99&op=1&day=${day}`);
    d.log(d.find());
  }
}

register("新春登录礼", 新春登录礼);

async function 爱的同心结(d) {
  var _id, config, count, data, uin;
  config = d.config("爱的同心结.QQ");
  if ((config !== null)) {
    for (let uin of config) {
      await d.get(`cmd=loveknot&sub=3&uin=${uin}`);
      d.log(d.find());
      if ((contains(d.html, "你当前没有同心结哦"))) {
        break;
      }
    }
  }
  data = ({["4016"]: 2, ["4015"]: 4, ["4014"]: 10, ["4013"]: 16, ["4012"]: 20});
  for (let [_id, count] of pyItems(data)) {
    for (let _ of pyRange(count)) {
      await d.get(`cmd=loveknot&sub=2&id=${_id}`);
      d.log(d.find());
      if ((!contains(d.html, "恭喜您兑换成功"))) {
        break;
      }
    }
  }
}

register("爱的同心结", 爱的同心结);

async function 重阳太白诗会(d) {
  await d.get("cmd=newAct&subtype=168&op=2");
  d.log(d.find("<br /><br />(.*?)<br />"));
}

register("重阳太白诗会", 重阳太白诗会);

const __globals = { 邪神秘宝: 邪神秘宝, 星盘: 星盘, 帮派商会: 帮派商会, 任务派遣中心: 任务派遣中心, 侠士客栈: 侠士客栈, _run_dream_instance: _run_dream_instance, JiangHuDream: JiangHuDream, 柒承的忙碌日常: 柒承的忙碌日常, 群英拭剑谁为峰: 群英拭剑谁为峰, 时空守护者: 时空守护者, 倚天屠龙归我心: 倚天屠龙归我心, 神雕侠侣: 神雕侠侣, 雪山藏魂: 雪山藏魂, 桃花自古笑春风: 桃花自古笑春风, 战乱襄阳: 战乱襄阳, 天涯浪子: 天涯浪子, 全真古墓意难平: 全真古墓意难平, 南海有岛名侠客: 南海有岛名侠客, 老鹅的圣诞冒险: 老鹅的圣诞冒险, 世外桃源梦一场: 世外桃源梦一场, 中原武林之危: 中原武林之危, 世界树轮回秘境: 世界树轮回秘境, 技冠五绝: 技冠五绝, 江湖长梦: 江湖长梦, 深渊之潮: 深渊之潮, 侠客岛: 侠客岛, 龙凰之境: 龙凰之境, 背包: 背包, 镶嵌: 镶嵌, 普通合成: 普通合成, 符石分解: 符石分解, 符石打造: 符石打造, 神匠坊: 神匠坊, 每日宝箱: 每日宝箱, 猜单双: 猜单双, 煮元宵: 煮元宵, 元宵节: 元宵节, 刮刮卡: 刮刮卡, 娃娃机: 娃娃机, 吉利兑: 吉利兑, 激运牌: 激运牌, 回忆录: 回忆录, 愚人节: 愚人节, 疯狂许愿: 疯狂许愿, 儿童节: 儿童节, 开学季: 开学季, 大笨钟: 大笨钟, 幸运金蛋: 幸运金蛋, 客栈同福: 客栈同福, 斗神塔: 斗神塔, 节日福利: 节日福利, 双旦福利: 双旦福利, 金秋福利: 金秋福利, 春节福利: 春节福利, 多倍福利: 多倍福利, 新春拜年: 新春拜年, 神魔转盘: 神魔转盘, 乐斗驿站: 乐斗驿站, 幸运转盘: 幸运转盘, 冰雪企缘: 冰雪企缘, 甜蜜夫妻: 甜蜜夫妻, 乐斗菜单: 乐斗菜单, 周周礼包: 周周礼包, 登录有礼: 登录有礼, 活跃礼包: 活跃礼包, 清明上香: 清明上香, 徽章战令: 徽章战令, 生肖福卡_好友赠卡: 生肖福卡_好友赠卡, 生肖福卡_分享福卡: 生肖福卡_分享福卡, 生肖福卡_领取福卡: 生肖福卡_领取福卡, 生肖福卡_合卡: 生肖福卡_合卡, 生肖福卡_抽奖: 生肖福卡_抽奖, 生肖福卡: 生肖福卡, 长安盛会: 长安盛会, 深渊秘宝: 深渊秘宝, 中秋礼盒: 中秋礼盒, 双节签到: 双节签到, 斗境探秘: 斗境探秘, 春联大赛: 春联大赛, 预热礼包: 预热礼包, 豪侠出世: 豪侠出世, 乐斗游记: 乐斗游记, 喜从天降: 喜从天降, 微信兑换: 微信兑换, 浩劫宝箱: 浩劫宝箱, 端午有礼: 端午有礼, 圣诞有礼: 圣诞有礼, 新春礼包: 新春礼包, 登录商店: 登录商店, 盛世巡礼: 盛世巡礼, 五一礼包: 五一礼包, 五一预订: 五一预订, 好礼提升: 好礼提升, 周年祝福: 周年祝福, 周年预热: 周年预热, 年兽大作战: 年兽大作战, 新春登录礼: 新春登录礼, 爱的同心结: 爱的同心结, 重阳太白诗会: 重阳太白诗会 };
export { 邪神秘宝, 星盘, 帮派商会, 任务派遣中心, 侠士客栈, _run_dream_instance, JiangHuDream, 柒承的忙碌日常, 群英拭剑谁为峰, 时空守护者, 倚天屠龙归我心, 神雕侠侣, 雪山藏魂, 桃花自古笑春风, 战乱襄阳, 天涯浪子, 全真古墓意难平, 南海有岛名侠客, 老鹅的圣诞冒险, 世外桃源梦一场, 中原武林之危, 世界树轮回秘境, 技冠五绝, 江湖长梦, 深渊之潮, 侠客岛, 龙凰之境, 背包, 镶嵌, 普通合成, 符石分解, 符石打造, 神匠坊, 每日宝箱, 猜单双, 煮元宵, 元宵节, 刮刮卡, 娃娃机, 吉利兑, 激运牌, 回忆录, 愚人节, 疯狂许愿, 儿童节, 开学季, 大笨钟, 幸运金蛋, 客栈同福, 斗神塔, 节日福利, 双旦福利, 金秋福利, 春节福利, 多倍福利, 新春拜年, 神魔转盘, 乐斗驿站, 幸运转盘, 冰雪企缘, 甜蜜夫妻, 乐斗菜单, 周周礼包, 登录有礼, 活跃礼包, 清明上香, 徽章战令, 生肖福卡_好友赠卡, 生肖福卡_分享福卡, 生肖福卡_领取福卡, 生肖福卡_合卡, 生肖福卡_抽奖, 生肖福卡, 长安盛会, 深渊秘宝, 中秋礼盒, 双节签到, 斗境探秘, 春联大赛, 预热礼包, 豪侠出世, 乐斗游记, 喜从天降, 微信兑换, 浩劫宝箱, 端午有礼, 圣诞有礼, 新春礼包, 登录商店, 盛世巡礼, 五一礼包, 五一预订, 好礼提升, 周年祝福, 周年预热, 年兽大作战, 新春登录礼, 爱的同心结, 重阳太白诗会 };
