// This file is generated by scripts/generate_cloudflare_worker_js.py.
// Do not edit it by hand; edit src/tasks/*.py and regenerate.

import { DateTime, Registry, TaskModule, contains, pyAdd, pyAny, pyCount, pyDict, pyDivmod, pyEnumerate, pyGet, pyInt, pyIsSubset, pyItems, pyLen, pyMax, pyMin, pyRange, pySet, pySlice, pySorted, pyStr, pyTruthy, randomChoice, randomSample, sleep } from '../runtime.js';
import { c_get_material_quantity, c_get_doushenta_cd, c_邪神秘宝, c_帮派商会, c_任务派遣中心, c_侠士客栈, c_帮派巡礼, c_深渊秘境, c_龙凰论武, c_幸运金蛋, c_客栈同福, c_大笨钟, c_领取今日活跃度奖励 } from './common.js';

const registry = new Registry(TaskModule.noon);
const register = (taskName, taskFunc) => registry.register(taskName, taskFunc);
async function 邪神秘宝(d) {
  await c_邪神秘宝(d);
}

register("邪神秘宝", 邪神秘宝);

async function 华山论剑(d) {
  var _id, configured_knights, count, exchange_config, i, item, knight, knight_config, knight_data, knight_id, knight_name, knights, quantity, quotient, remainder, selected_knights;
  if (!pyTruthy((1 <= DateTime.day() && DateTime.day() <= 26))) {
    return;
  }
  if ((DateTime.day() === 26)) {
    await d.get("cmd=knightarena&op=drawranking");
    d.log(d.find());
    exchange_config = d.config("华山论剑.exchange");
    for (let [_id, item] of pyItems(exchange_config)) {
      quantity = item["quantity"];
      if ((quantity <= 0)) {
        continue;
      }
      [quotient, remainder] = pyDivmod(quantity, 10);
      for (let _ of pyRange(quotient)) {
        await d.get(`cmd=knightarena&op=exchange&id=${_id}&times=10`);
        d.log(d.find());
        if ((!contains(d.html, "成功"))) {
          break;
        }
      }
      for (let _ of pyRange(remainder)) {
        await d.get(`cmd=knightarena&op=exchange&id=${_id}&times=1`);
        d.log(d.find());
        if ((!contains(d.html, "成功"))) {
          break;
        }
      }
    }
    return;
  }
  knight_config = d.config("华山论剑.战阵调整");
  if ((knight_config === null)) {
    d.log("你没有设置战阵调整，跳过挑战");
    return;
  }
  await d.get("cmd=knightarena&op=viewsetknightlist&pos=0");
  knight_data = ({});
  for (let [knight_name, knight_id] of d.findall(">\\s*([^<>\\s][^<>]*?)(?:&nbsp;|\\s)+\\d+级.*?knightid=(\\d+)")) {
    knight_data[knight_name] = knight_id;
  }
  if (!pyTruthy(knight_data)) {
    d.log("战阵调整侠士不足，跳过挑战");
    return;
  }
  for (let item of knight_config) {
    count = item["count"];
    knights = item["knights"];
    configured_knights = pySlice(knights, null, 3);
    selected_knights = [];
    if ((pyLen(configured_knights) < 3)) {
      d.log("当前编队配置侠士不足3个，跳过该编队挑战");
      continue;
    }
    for (let knight of configured_knights) {
      if (pyTruthy((_id = pyGet(knight_data, knight, null)))) {
        selected_knights.push([knight, _id]);
      } else {
        d.log(`配置侠士缺失 -> ${knight}`);
      }
    }
    if ((pyLen(selected_knights) < 3)) {
      d.log("当前编队出战侠士不足3个，跳过该编队挑战");
      continue;
    }
    for (let [i, item] of pyEnumerate(selected_knights, 1)) {
      [knight, _id] = item;
      await d.get(`cmd=knightarena&op=setknight&id=${_id}&pos=${i}&type=1`);
      d.log(`第${i}战 -> ${knight}`);
    }
    for (let _ of pyRange(count)) {
      await d.get("cmd=knightarena&op=challenge");
      d.log(d.find());
      if ((!contains(d.html, "增加荣誉点数"))) {
        break;
      }
    }
  }
}

register("华山论剑", 华山论剑);

async function 分享(d) {
  var is_end, s, second;
  is_end = false;
  second = await c_get_doushenta_cd(d);
  await d.get("cmd=sharegame&subtype=1");
  for (let _ of pyRange(9)) {
    await d.get("cmd=sharegame&subtype=6");
    d.log(d.find("】</p>(.*?)<p>"));
    if (((contains(d.html, "达到当日分享次数上限")) || pyTruthy(is_end))) {
      d.log(d.find("</p><p>(.*?)<br />"));
      break;
    }
    for (let _ of pyRange(10)) {
      await d.get("cmd=towerfight&type=0");
      d.log(`斗神塔 -> ${d.find()}`);
      await sleep(second);
      if ((!contains(d.html, "您战胜了"))) {
        is_end = true;
        break;
      }
    }
  }
  await d.get("cmd=towerfight&type=11");
  d.log(`斗神塔 -> ${d.find()}`);
  await sleep(second);
  if ((contains(d.html, "结束挑战"))) {
    await d.get("cmd=towerfight&type=7");
    d.log(`斗神塔 -> ${d.find()}`);
  }
  if ((DateTime.week() !== 4)) {
    return;
  }
  await d.get("cmd=sharegame&subtype=3");
  for (let s of d.findall("sharenums=(\\d+)")) {
    await d.get(`cmd=sharegame&subtype=4&sharenums=${s}`);
    d.log(d.find("】</p>(.*?)<p>"));
  }
  if ((pyCount(d.html, "已领取") === 14)) {
    await d.get("cmd=sharegame&subtype=7");
    d.log(d.find("】</p>(.*?)<p>"));
  }
}

register("分享", 分享);

async function 好友(d) {
  var count, fight_count, fight_success_count, friend_ids, ids, page, u;
  count = d.config("好友.贡献药水.count");
  fight_count = d.config("好友.乐斗次数");
  for (let _ of pyRange(count)) {
    await d.get("cmd=use&id=3038&store_type=1&page=1");
    if ((contains(d.html, "使用规则"))) {
      d.log(d.find("】</p><p>(.*?)<br />"));
      break;
    }
    d.log(d.find());
  }
  friend_ids = [];
  for (let page of pyRange(2, 12)) {
    await d.get(`cmd=friendlist&page=${page}`);
    ids = d.findall("\\d+：.*?cmd=fight&amp;B_UID=(\\d+).*?>乐斗</a>");
    if (!pyTruthy(ids)) {
      if ((page === 2)) {
        d.log("没有可乐斗好友");
      }
      break;
    }
    friend_ids.push(...ids);
    if ((pyLen(friend_ids) >= fight_count)) {
      break;
    }
  }
  if (!pyTruthy(friend_ids)) {
    return;
  }
  fight_success_count = 0;
  for (let u of pySlice(friend_ids, null, fight_count)) {
    await d.get(`cmd=fight&B_UID=${u}`);
    if ((contains(d.html, "使用规则"))) {
      d.log(d.find("】</p><p>(.*?)<br />"));
      if ((contains(d.html, "体力值不足"))) {
        break;
      }
      continue;
    }
    d.log(d.find("<br />(.*?)，"));
    fight_success_count = pyAdd(fight_success_count, 1);
    if ((contains(d.html, "体力值不足"))) {
      break;
    }
  }
  d.log(`好友乐斗 -> ${fight_success_count}/${fight_count}`);
}

register("好友", 好友);

async function 帮友(d) {
  var u;
  await d.get("cmd=viewmem&page=1");
  for (let u of d.findall("侠：.*?B_UID=(\\d+)")) {
    await d.get(`cmd=fight&B_UID=${u}`);
    d.log(d.find("<br />(.*?)，"));
  }
}

register("帮友", 帮友);

async function 侠侣(d) {
  var enabled, u, uin;
  enabled = d.config("侠侣.情师徒拜.enabled");
  await d.get("cmd=viewxialv&page=1");
  if (pyTruthy(enabled)) {
    uin = d.findall("</a>\\d+.*?B_UID=(\\d+)");
  } else {
    uin = d.findall("侠：.*?B_UID=(\\d+)");
  }
  for (let u of uin) {
    await d.get(`cmd=fight&B_UID=${u}`);
    if ((contains(d.html, "使用规则"))) {
      d.log(d.find("】</p><p>(.*?)<br />"));
    } else {
      d.log(d.find("<br />(.*?)！"));
    }
    if ((contains(d.html, "体力值不足"))) {
      break;
    }
  }
  if ((!contains(pySet([2, 5, 7]), DateTime.week()))) {
    return;
  }
  await d.get("cmd=cfight&subtype=9");
  if ((contains(d.html, "使用规则"))) {
    d.log(d.find("】</p><p>(.*?)<br />"));
  } else {
    d.log(d.find("报名状态.*?<br />(.*?)<br />"));
  }
}

register("侠侣", 侠侣);

async function 武林(d) {
  await d.get("cmd=fastSignWulin&ifFirstSign=1");
  if ((contains(d.html, "使用规则"))) {
    d.log(d.find("】</p><p>(.*?)<br />"));
  } else {
    d.log(d.find("升级。<br />(.*?) "));
  }
}

register("武林", 武林);

async function 群侠(d) {
  var _id, i, knight, knight_config, knight_data;
  knight_config = d.config("群侠.设置战队");
  if ((knight_config === null)) {
    d.log("你必须设置战队才能报名");
    return;
  }
  await d.get("cmd=knightfight&op=viewsetknightlist&pos=0");
  if ((contains(d.html, "报名状态：已报名"))) {
    d.log(d.find("报名状态：(.*?)<"));
    return;
  }
  knight_data = pyDict(d.findall(">([\\u4e00-\\u9fff]+) \\d+级.*?knightid=(\\d+)"));
  if (!pyTruthy(knight_data)) {
    d.log("设置战队侠士不足");
    return;
  }
  for (let [i, knight] of pyEnumerate(knight_config, 1)) {
    if ((i > 5)) {
      break;
    }
    if (pyTruthy((_id = pyGet(knight_data, knight, null)))) {
      await d.get(`cmd=knightfight&op=set_knight&id=${_id}&pos=${i}&type=1`);
      d.log(`第${i}战 -> ${knight}`);
    } else {
      d.log(`第${i}战 -> 您没有${knight}，跳过报名`);
      return;
    }
  }
  await d.get("cmd=knightfight&op=signup");
  d.log(d.find("侠士侠号.*?<br />(.*?)<br />"));
}

register("群侠", 群侠);

async function 结拜(d) {
  var _id;
  if ((!contains(pySet([1, 2]), DateTime.week()))) {
    return;
  }
  for (let _id of [1, 2, 3, 5, 4]) {
    await d.get(`cmd=brofight&subtype=1&gidIdx=${_id}`);
    d.log(d.find("排行</a><br />(.*?)<"));
    if (((contains(d.html, "请换一个赛区报名")) || (contains(d.html, "你们无法报名")))) {
      continue;
    }
    break;
  }
}

register("结拜", 结拜);

async function 巅峰之战进行中(d) {
  var _id;
  if ((contains(pySet([1, 2]), DateTime.week()))) {
    await d.get("cmd=gvg&sub=1");
    d.log(d.find("】</p>(.*?)<br />"));
    _id = d.config("巅峰之战进行中.id");
    await d.get(`cmd=gvg&sub=4&group=${_id}&check=1`);
    d.log(d.find("】</p>(.*?)<br />"));
    return;
  }
  for (let _ of pyRange(14)) {
    await d.get("cmd=gvg&sub=5");
    if ((contains(d.html, "战线告急"))) {
      d.log(d.find("支援！<br />(.*?)<"));
    } else {
      d.log(d.find("】</p>(.*?)<"));
    }
    if ((!contains(d.html, "你在巅峰之战中"))) {
      break;
    }
  }
}

register("巅峰之战进行中", 巅峰之战进行中);

async function 矿洞(d) {
  var _id, f, is_success, m, mercenary_all, mercenary_battle, mercenary_ids, mercenary_name;
  f = d.config("矿洞.floor");
  m = d.config("矿洞.mode");
  await d.get("cmd=newmercenary");
  mercenary_ids = [];
  mercenary_all = d.findall("id=(\\d+)\">(.*?)</a>");
  mercenary_battle = d.findall("<br />\\d+. (.*?) ");
  for (let [_id, mercenary_name] of mercenary_all) {
    if ((contains(mercenary_battle, mercenary_name))) {
      mercenary_ids.push(_id);
    }
  }
  if ((contains(d.html, "10019"))) {
    await d.get("cmd=newmercenary&sub=3&id=10019");
    d.log(`${d.find("！<br />(.*?)<")} -> ${d.find()}`);
    is_success = true;
  } else {
    is_success = false;
  }
  await d.get("cmd=factionmine");
  for (let _ of pyRange(5)) {
    if ((contains(d.html, "副本挑战中"))) {
      await d.get("cmd=factionmine&op=fight");
      d.log(d.find());
      if ((contains(d.html, "挑战次数不足"))) {
        break;
      }
      await sleep(1.5);
    } else if ((contains(d.html, "开启副本"))) {
      await d.get(`cmd=factionmine&op=start&floor=${f}&mode=${m}`);
      d.log(d.find());
      if ((contains(d.html, "当前不能开启此副本"))) {
        break;
      }
    } else if ((contains(d.html, "领取奖励"))) {
      await d.get("cmd=factionmine&op=reward");
      d.log(d.find());
    }
  }
  if (!pyTruthy(is_success)) {
    return;
  }
  for (let _id of mercenary_ids) {
    await d.get(`cmd=newmercenary&sub=3&id=${_id}`);
    d.log(`恢复${d.find("！<br />(.*?)<")} -> ${d.find()}`);
  }
}

register("矿洞", 矿洞);

async function 掠夺(d) {
  var _id, data, gra_id, zhanli;
  if ((DateTime.week() === 3)) {
    await d.get("cmd=forage_war&subtype=6");
    d.log(d.find());
    await d.get("cmd=forage_war&subtype=1");
    d.log(d.find());
    return;
  }
  if ((DateTime.week() !== 2)) {
    return;
  }
  await d.get("cmd=forage_war");
  if (((contains(d.html, "本轮轮空")) || (contains(d.html, "未报名")))) {
    d.log(d.find("本届战况：(.*?)<br />"));
    return;
  }
  data = [];
  await d.get("cmd=forage_war&subtype=3");
  if (pyTruthy((gra_id = d.findall("gra_id=(\\d+)\">掠夺")))) {
    for (let _id of gra_id) {
      await d.get(`cmd=forage_war&subtype=3&op=1&gra_id=${_id}`);
      if (pyTruthy((zhanli = d.find("<br />1.*? (\\d+)\\.")))) {
        data.push([pyInt(zhanli), _id]);
      }
    }
    if (pyTruthy(data)) {
      [_, _id] = pyMin(data, null);
      await d.get(`cmd=forage_war&subtype=4&gra_id=${_id}`);
      d.log(d.find());
    }
  } else {
    d.log("已占领对方全部粮仓");
  }
  await d.get("cmd=forage_war&subtype=5");
  d.log(d.find());
}

register("掠夺", 掠夺);

async function 踢馆(d) {
  var t;
  if ((DateTime.week() === 6)) {
    await d.get("cmd=facchallenge&subtype=1");
    d.log(d.find());
    await d.get("cmd=facchallenge&subtype=7");
    d.log(d.find());
    return;
  }
  if ((DateTime.week() !== 5)) {
    return;
  }
  function* generate_sequence() {
    var t;
    for (let t of [2, 2, 2, 2, 2, 4]) {
      yield t;
    }
    for (let _ of pyRange(30)) {
      yield 3;
    }
  }
  for (let t of generate_sequence()) {
    await d.get(`cmd=facchallenge&subtype=${t}`);
    d.log(d.find());
    if ((contains(d.html, "您的复活次数已耗尽"))) {
      break;
    } else if ((contains(d.html, "您的挑战次数已用光"))) {
      break;
    } else if ((contains(d.html, "你们帮没有报名参加这次比赛"))) {
      break;
    }
  }
}

register("踢馆", 踢馆);

async function 竞技场(d) {
  if (!pyTruthy((1 <= DateTime.day() && DateTime.day() <= 25))) {
    return;
  }
  if (pyTruthy(d.config("竞技场.河图洛书.enabled"))) {
    await d.get("cmd=arena&op=exchange&id=5435&times=10");
    d.log(d.find());
  }
  for (let _ of pyRange(10)) {
    await d.get("cmd=arena&op=challenge");
    d.log(d.find());
    if ((contains(d.html, "免费挑战次数已用完"))) {
      break;
    }
  }
  await d.get("cmd=arena&op=drawdaily");
  d.log(d.find());
}

register("竞技场", 竞技场);

async function 十二宫(d) {
  var _id;
  _id = d.config("十二宫.id");
  await d.get(`cmd=zodiacdungeon&op=autofight&scene_id=${_id}`);
  if ((contains(d.html, "恭喜你"))) {
    d.log(d.find("恭喜你，(.*?)！"));
    return;
  } else if ((contains(d.html, "是否复活再战"))) {
    d.log(d.find("<br.*>(.*?)，"));
    return;
  }
  d.log(d.find("<p>(.*?)<br />"));
}

register("十二宫", 十二宫);

async function 许愿(d) {
  var sub;
  for (let sub of [5, 1, 6]) {
    await d.get(`cmd=wish&sub=${sub}`);
    d.log(d.find());
  }
}

register("许愿", 许愿);

async function 抢地盘(d) {
  var _id, manorid;
  await d.get("cmd=recommendmanor&type=11&page=1");
  if (pyTruthy((manorid = d.findall("manorid=(\\d+)\">攻占</a>")))) {
    _id = randomChoice(manorid);
    await d.get(`cmd=manorfight&fighttype=1&manorid=${_id}`);
    d.log(d.find("</p><p>(.*?)。"));
  }
}

register("抢地盘", 抢地盘);

async function 历练(d) {
  var _id, config, count;
  config = d.config("历练");
  await d.get("cmd=view&type=6");
  if ((contains(d.html, "取消自动使用活力药水"))) {
    await d.get("cmd=set&type=11");
    d.log("取消自动使用活力药水");
  }
  for (let [_id, count] of pyItems(config)) {
    if ((count <= 0)) {
      continue;
    }
    for (let _ of pyRange(count)) {
      await d.get(`cmd=mappush&subtype=3&mapid=6&npcid=${_id}&pageid=2`);
      if ((contains(d.html, "您还没有打到该历练场景"))) {
        d.log(d.find("介绍</a><br />(.*?)<br />"));
        break;
      }
      d.log(d.find("阅历值：\\d+<br />(.*?)<br />"));
      if ((contains(d.html, "活力不足"))) {
        return;
      } else if ((!contains(d.html, "BOSS"))) {
        break;
      }
    }
  }
}

register("历练", 历练);

async function 镖行天下(d) {
  var count, result, u;
  await d.get("cmd=cargo");
  if ((contains(d.html, "护送完成"))) {
    await d.get("cmd=cargo&op=16");
    d.log(d.find());
  }
  if ((contains(d.html, "剩余护送次数：1"))) {
    await d.get("cmd=cargo&op=7");
    if (pyTruthy((result = d.find("免费刷新次数：(\\d+)")))) {
      count = pyInt(result);
    } else {
      d.log("获取免费刷新次数失败，免费次数重置为0");
      count = 0;
    }
    for (let _ of pyRange(count)) {
      d.log(d.find("当前镖师：(.*?)<"));
      if ((!contains(d.html, "蔡八斗"))) {
        break;
      }
      await d.get("cmd=cargo&op=8");
      d.log(d.find());
    }
    await d.get("cmd=cargo&op=6");
    d.log(d.find());
  }
  for (let _ of pyRange(10)) {
    await d.get("cmd=cargo&op=3");
    d.log(d.find());
    if ((contains(d.html, "刷新过于频繁"))) {
      await sleep(2);
      continue;
    }
    for (let u of d.findall("passerby_uin=(\\d+)\">拦截")) {
      await d.get(`cmd=cargo&op=14&passerby_uin=${u}`);
      d.log(d.find());
      if ((contains(d.html, "剩余拦截次数：0"))) {
        return;
      }
    }
  }
}

register("镖行天下", 镖行天下);

async function 幻境(d) {
  var _id, b_id;
  await d.get("cmd=misty");
  if ((contains(d.html, "挑战次数：0/1"))) {
    d.log("您的挑战次数已用完，请明日再战！");
    return;
  }
  if (((contains(d.html, "累积星数")) && (contains(d.html, "op=return")))) {
    await d.get("cmd=misty&op=return");
  }
  _id = d.config("幻境.id");
  await d.get(`cmd=misty&op=start&stage_id=${_id}`);
  if ((contains(d.html, "副本未开通"))) {
    d.log(`${_id} -> 副本未开通`);
    return;
  }
  for (let _ of pyRange(5)) {
    await d.get("cmd=misty&op=fight");
    d.log(d.find("星数.*?<br />(.*?)<br />"));
    if ((contains(d.html, "尔等之才"))) {
      break;
    }
  }
  for (let _ of pyRange(10)) {
    b_id = d.find("box_id=(\\d+)");
    if ((b_id === null)) {
      break;
    }
    await d.get(`cmd=misty&op=reward&box_id=${b_id}`);
    d.log(d.find("星数.*?<br />(.*?)<br />"));
  }
  await d.get("cmd=misty&op=return");
}

register("幻境", 幻境);

async function 群雄逐鹿(d) {
  var op;
  if ((DateTime.week() !== 6)) {
    return;
  }
  for (let op of ["signup", "drawreward"]) {
    await d.get(`cmd=thronesbattle&op=${op}`);
    d.log(d.find("届群雄逐鹿<br />(.*?)<br />"));
  }
}

register("群雄逐鹿", 群雄逐鹿);

async function 画卷迷踪(d) {
  for (let _ of pyRange(20)) {
    await d.get("cmd=scroll_dungeon&op=fight&buff=0");
    d.log(d.find("</a><br /><br />(.*?)<br />"));
    if ((contains(d.html, "没有挑战次数"))) {
      break;
    } else if ((contains(d.html, "征战书不足"))) {
      break;
    }
  }
}

register("画卷迷踪", 画卷迷踪);

async function 门派(d) {
  var _id, name, op, ops, rank, ranks, task_id, tasks, uin, url, wuhuatang;
  if (pyTruthy(d.config("门派.门派高香.enabled"))) {
    await d.get("cmd=exchange&subtype=2&type=1248&times=1");
    d.log(d.find());
  }
  for (let op of ["fumigatefreeincense", "fumigatepaidincense"]) {
    await d.get(`cmd=sect&op=${op}`);
    d.log(d.find("修行。<br />(.*?)<br />"));
  }
  ops = ["trainingwithnpc", "trainingwithmember"];
  if (pyTruthy(d.config("门派.门派战书.enabled"))) {
    await d.get("cmd=exchange&subtype=2&type=1249&times=1");
    d.log(d.find());
    if ((contains(d.html, "成功"))) {
      ops.push("trainingwithmember");
    }
  }
  for (let op of ops) {
    await d.get(`cmd=sect&op=${op}`);
    d.log(d.find());
  }
  ranks = ["rank=1&pos=1", "rank=2&pos=1", "rank=2&pos=2", "rank=3&pos=1", "rank=3&pos=2", "rank=3&pos=3", "rank=3&pos=4"];
  for (let rank of ranks) {
    await d.get(`cmd=sect&op=trainingwithcouncil&${rank}`);
    d.log(d.find());
  }
  wuhuatang = await d.get("cmd=sect_task");
  tasks = ({["进入华藏寺看一看"]: "cmd=sect_art", ["进入伏虎寺看一看"]: "cmd=sect_trump", ["进入金顶看一看"]: "cmd=sect&op=showcouncil", ["进入八叶堂看一看"]: "cmd=sect&op=showtraining", ["进入万年寺看一看"]: "cmd=sect&op=showfumigate"});
  for (let [name, url] of pyItems(tasks)) {
    if ((contains(wuhuatang, name))) {
      await d.get(url);
      d.log(name);
    }
  }
  if ((contains(wuhuatang, "查看一名"))) {
    d.log("查看好友第二页所有成员");
    await d.get("cmd=friendlist&page=2");
    for (let uin of d.findall("</a>\\d+.*?B_UID=(\\d+)")) {
      await d.get(`cmd=totalinfo&B_UID=${uin}`);
      d.log(`查看好友 -> ${uin}`);
    }
  }
  if ((contains(wuhuatang, "进行一次心法修炼"))) {
    for (let _id of pyRange(101, 119)) {
      await d.get(`cmd=sect_art&subtype=2&art_id=${_id}&times=1`);
      d.log(d.find());
      if ((contains(d.html, "修炼成功"))) {
        break;
      }
    }
  }
  await d.get("cmd=sect_task");
  for (let task_id of d.findall("task_id=(\\d+)\">完成")) {
    await d.get(`cmd=sect_task&subtype=2&task_id=${task_id}`);
    d.log(d.find());
  }
}

register("门派", 门派);

async function 门派邀请赛(d) {
  var _id, exchange_config, item, quantity, quotient, remainder;
  if ((contains(pySet([1, 2]), DateTime.week()))) {
    await d.get("cmd=secttournament&op=signup");
    d.log(d.find());
    await d.get("cmd=secttournament&op=getrankandrankingreward");
    d.log(d.find());
    return;
  }
  exchange_config = d.config("门派邀请赛.exchange");
  for (let [_id, item] of pyItems(exchange_config)) {
    quantity = item["quantity"];
    if ((quantity <= 0)) {
      continue;
    }
    [quotient, remainder] = pyDivmod(quantity, 10);
    for (let _ of pyRange(quotient)) {
      await d.get(`cmd=exchange&subtype=2&type=${_id}&times=10`);
      d.log(d.find());
      if ((!contains(d.html, "成功"))) {
        break;
      }
    }
    for (let _ of pyRange(remainder)) {
      await d.get(`cmd=exchange&subtype=2&type=${_id}&times=1`);
      d.log(d.find());
      if ((!contains(d.html, "成功"))) {
        break;
      }
    }
  }
  for (let _ of pyRange(10)) {
    await d.get("cmd=secttournament&op=fight");
    d.log(d.find());
    if ((contains(d.html, "已达最大挑战上限"))) {
      break;
    } else if ((contains(d.html, "门派战书不足"))) {
      break;
    }
  }
}

register("门派邀请赛", 门派邀请赛);

async function 会武(d) {
  var _id, exchange_config, item, quantity, quotient, remainder;
  if ((contains(pySet([1, 2, 3]), DateTime.week()))) {
    for (let _ of pyRange(21)) {
      await d.get("cmd=sectmelee&op=dotraining");
      if ((contains(d.html, "试炼场】"))) {
        d.log(d.find("最高伤害：\\d+<br />(.*?)<br />"));
        continue;
      }
      d.log(d.find("规则</a><br />(.*?)<br />"));
      if ((contains(d.html, "你已达今日挑战上限"))) {
        break;
      } else if (((contains(d.html, "你的试炼书不足")) && pyTruthy(d.config("会武.试炼书.enabled")))) {
        await d.get("cmd=exchange&subtype=2&type=1265&times=1&costtype=13");
        d.log(d.find());
        if ((!contains(d.html, "成功"))) {
          break;
        }
      }
    }
  } else if ((DateTime.week() === 4)) {
    await d.get("cmd=sectmelee&op=cheer&sect=1003");
    await d.get("cmd=sectmelee&op=showcheer");
    d.log(d.find());
    exchange_config = d.config("会武.exchange");
    for (let [_id, item] of pyItems(exchange_config)) {
      quantity = item["quantity"];
      if ((quantity <= 0)) {
        continue;
      }
      [quotient, remainder] = pyDivmod(quantity, 10);
      for (let _ of pyRange(quotient)) {
        await d.get(`cmd=exchange&subtype=2&type=${_id}&times=10&costtype=13`);
        d.log(d.find());
        if ((!contains(d.html, "成功"))) {
          break;
        }
      }
      for (let _ of pyRange(remainder)) {
        await d.get(`cmd=exchange&subtype=2&type=${_id}&times=1&costtype=13`);
        d.log(d.find());
        if ((!contains(d.html, "成功"))) {
          break;
        }
      }
    }
  } else if ((DateTime.week() === 6)) {
    await d.get("cmd=sectmelee&op=showreward");
    d.log(d.find("<br />(.*?)。"));
    d.log(d.find("。<br />(.*?)。"));
    await d.get("cmd=sectmelee&op=drawreward");
    if ((contains(d.html, "本届已领取奖励"))) {
      d.log(d.find("规则</a><br />(.*?)<br />"));
    } else {
      d.log(d.find());
    }
  }
}

register("会武", 会武);

async function 梦想之旅(d) {
  var b, bmapid, name, place, quantity, s;
  await d.get("cmd=dreamtrip&sub=2");
  d.log(d.find());
  if ((DateTime.week() !== 4)) {
    return;
  }
  quantity = d.config("梦想之旅.梦幻旅行.count");
  if ((pyCount(d.html, "已去过") < quantity)) {
    d.log(`已去过数量低于${quantity}`);
    return;
  }
  if (pyTruthy((place = d.findall("([\\u4e00-\\u9fa5\\s\\-]+)(?=\\s未去过)")))) {
    bmapid = d.find("bmapid=(\\d+)\">梦幻旅行");
    for (let name of place) {
      await d.get(`cmd=dreamtrip&sub=3&bmapid=${bmapid}`);
      s = d.find(`${name}.*?smapid=(\\d+)`);
      await d.get(`cmd=dreamtrip&sub=2&smapid=${s}`);
      d.log(d.find());
    }
  }
  for (let _ of pyRange(2)) {
    if (pyTruthy((b = d.findall("sub=4&amp;bmapid=(\\d+)")))) {
      await d.get(`cmd=dreamtrip&sub=4&bmapid=${b[0]}`);
      d.log(d.find());
    }
  }
}

register("梦想之旅", 梦想之旅);

async function 问鼎天下_商店兑换(d) {
  var _dict, _id, backpack_id, data, material_name, max_level, name, need, now_level, possess, q, r, t, treasure;
  name = "神魔录";
  data = ({["夔牛鼓"]: ({["id"]: 1, ["t"]: 1270, ["backpack_id"]: 5154, ["material_name"]: "夔牛碎片"}), ["饕餮鼎"]: ({["id"]: 2, ["t"]: 1271, ["backpack_id"]: 5155, ["material_name"]: "饕餮碎片"}), ["烛龙印"]: ({["id"]: 3, ["t"]: 1268, ["backpack_id"]: 5156, ["material_name"]: "烛龙碎片"}), ["黄鸟伞"]: ({["id"]: 4, ["t"]: 1269, ["backpack_id"]: 5157, ["material_name"]: "黄鸟碎片"})});
  for (let [treasure, _dict] of pyItems(data)) {
    _id = _dict["id"];
    t = _dict["t"];
    backpack_id = _dict["backpack_id"];
    material_name = _dict["material_name"];
    possess = await c_get_material_quantity(d, backpack_id);
    await d.get(`cmd=ancient_gods&op=4&id=${_id}`);
    now_level = d.find("等级：(\\d+)");
    max_level = d.find("最高提升至(\\d+)");
    d.log(`${treasure} -> 当前 ${now_level} 级`, name);
    d.log(`${treasure} -> 最高 ${max_level} 级`, name);
    if ((now_level === max_level)) {
      continue;
    }
    need = d.find("碎片\\*(\\d+)");
    if ((need === null)) {
      d.log(`${treasure} -> 获取${material_name}需要数量失败`);
      continue;
    }
    need = pyInt(need);
    if ((need <= possess)) {
      continue;
    }
    d.log(`${treasure} -> 消耗${material_name}*${need}（${possess}）`, name);
    [q, r] = pyDivmod((need - possess), 10);
    if (pyTruthy(q)) {
      await d.get(`cmd=exchange&subtype=2&type=${t}&times=10&costtype=14`);
      d.log(`${treasure} -> ${d.find()}`);
      return;
    }
    for (let _ of pyRange(r)) {
      await d.get(`cmd=exchange&subtype=2&type=${t}&times=1&costtype=14`);
      d.log(`${treasure} -> ${d.find()}`);
    }
  }
}

async function 问鼎天下_助威(d) {
  var _id, cheer_links, cheer_name, config_key, op, target_id, target_ids;
  await d.get("cmd=tbattle");
  cheer_links = d.findall("cmd=tbattle&amp;op=(cheerregionbattle|cheerchampionbattle)&amp;id=(\\d+)");
  if (!pyTruthy(cheer_links)) {
    cheer_name = d.find("助威帮派：(.*?)<");
    if ((cheer_name !== null)) {
      d.log(`助威帮派 -> ${cheer_name}`);
      return true;
    }
    return false;
  }
  target_ids = [];
  for (let config_key of ["问鼎天下.淘汰赛", "问鼎天下.排名赛"]) {
    target_id = d.config(config_key);
    if ((target_id !== null)) {
      target_ids.push(pyStr(target_id));
    }
  }
  if (!pyTruthy(target_ids)) {
    d.log("你没有设置助威帮派id");
    return false;
  }
  for (let [op, _id] of cheer_links) {
    if ((!contains(target_ids, _id))) {
      continue;
    }
    await d.get(`cmd=tbattle&op=${op}&id=${_id}`);
    d.log(d.find());
    return true;
  }
  d.log("页面没有配置的助威帮派");
  return false;
}

async function 问鼎天下(d) {
  var _id, count, is_cheered, region, remaining_occupy_count;
  if ((DateTime.week() === 1)) {
    await d.get("cmd=tbattle&op=drawreward");
    d.log(d.find());
    await 问鼎天下_商店兑换(d);
  }
  is_cheered = await 问鼎天下_助威(d);
  if ((contains(pySet([6, 7]), DateTime.week()))) {
    if (!pyTruthy(is_cheered)) {
      d.log("页面没有可助威入口");
    }
    return;
  }
  await d.get("cmd=tbattle");
  if ((contains(d.html, "放弃"))) {
    d.log("已有占领资源点，本任务结束");
    return;
  }
  if ((contains(d.html, "你占领的领地已经枯竭"))) {
    await d.get("cmd=tbattle&op=drawreleasereward");
    d.log(d.find());
  }
  remaining_occupy_count = d.find("剩余抢占次数：(\\d+)");
  if ((remaining_occupy_count === null)) {
    d.log("获取剩余抢占次数失败");
    return;
  }
  remaining_occupy_count = pyInt(remaining_occupy_count);
  if ((remaining_occupy_count === 0)) {
    d.log("没有抢占次数了");
    return;
  }
  region = d.config("问鼎天下.region");
  count = d.config("问鼎天下.count");
  if ((count >= remaining_occupy_count)) {
    count = pyMax(0, null);
  }
  await d.get(`cmd=tbattle&op=showregion&region=${region}`);
  for (let _id of pySlice(d.findall("id=(\\d+).*?攻占</a>"), null, 4)) {
    while (pyTruthy(count)) {
      await d.get(`cmd=tbattle&op=occupy&id=${_id}&region=${region}`);
      d.log(d.find());
      if ((contains(d.html, "你主动与"))) {
        count -= 1;
        if ((contains(d.html, "放弃"))) {
          await d.get("cmd=tbattle&op=abandon");
          d.log(d.find());
        }
      } else {
        break;
      }
    }
    if ((count === 0)) {
      break;
    }
  }
  await d.get(`cmd=tbattle&op=showregion&region=${region}`);
  _id = d.findall("id=(\\d+).*?攻占</a>")[(-1)];
  await d.get(`cmd=tbattle&op=occupy&id=${_id}&region=1`);
  d.log(d.find());
}

register("问鼎天下", 问鼎天下);

async function 帮派商会(d) {
  await c_帮派商会(d);
}

register("帮派商会", 帮派商会);

async function 帮派远征军_攻击(d, p_id, u) {
  await d.get(`cmd=factionarmy&op=fightWithUsr&point_id=${p_id}&opp_uin=${u}`);
  if ((contains(d.html, "加入帮派第一周不能参与帮派远征军"))) {
    return false;
  }
  if ((contains(d.html, "【帮派远征军-征战结束】"))) {
    d.log(d.find());
    if ((contains(d.html, "您未能战胜"))) {
      return false;
    }
  } else if ((contains(d.html, "【帮派远征军】"))) {
    d.log(d.find("<br /><br />(.*?)</p>"));
    if ((contains(d.html, "您的血量不足"))) {
      return false;
    }
  }
  return true;
}

async function 帮派远征军_领取(d) {
  var _id, i_id, land_ids, p_id, point_ids;
  point_ids = [];
  land_ids = [];
  for (let _id of pyRange(5)) {
    await d.get(`cmd=factionarmy&op=viewIndex&island_id=${_id}`);
    point_ids = pyAdd(point_ids, d.findall("point_id=(\\d+)\">领取奖励"));
    if ((contains(d.html, "未解锁"))) {
      break;
    }
    land_ids = pyAdd(land_ids, d.findall("island_id=(\\d+)\">领取岛屿宝箱"));
  }
  for (let p_id of point_ids) {
    await d.get(`cmd=factionarmy&op=getPointAward&point_id=${p_id}`);
    d.log(d.find());
  }
  for (let i_id of land_ids) {
    await d.get(`cmd=factionarmy&op=getIslandAward&island_id=${i_id}`);
    d.log(d.find());
  }
}

async function 帮派远征军(d) {
  var data, p_id, pages, u;
  while (pyTruthy(true)) {
    await d.get("cmd=factionarmy&op=viewIndex&island_id=-1");
    p_id = d.find("point_id=(\\d+)\">参战");
    if ((p_id === null)) {
      d.log("已经全部通关了");
      await 帮派远征军_领取(d);
      break;
    }
    await d.get(`cmd=factionarmy&op=viewpoint&point_id=${p_id}`);
    data = [];
    for (let _ of pyRange(20)) {
      data = pyAdd(data, d.findall("(\\d+)\\.\\d+<a.*?opp_uin=(\\d+)\">攻击"));
      pages = d.find("pages=(\\d+)\">下一页");
      if ((!pyTruthy(data) || (pages === null))) {
        break;
      }
      await d.get(`cmd=factionarmy&op=viewpoint&point_id=${p_id}&page=${pages}`);
    }
    for (let [_, u] of pySorted(data, (x) => pyInt(x[0]))) {
      if (!pyTruthy(await 帮派远征军_攻击(d, p_id, u))) {
        await 帮派远征军_领取(d);
        return;
      }
    }
  }
}

register("帮派远征军", 帮派远征军);

async function 帮派黄金联赛_参战(d) {
  var _pages, data, p, pages, u;
  await d.get("cmd=factionleague&op=2");
  if ((!contains(d.html, "opp_uin"))) {
    d.log("敌人已全部阵亡");
    return;
  }
  data = [];
  if (pyTruthy((pages = d.find("pages=(\\d+)\">末页")))) {
    _pages = pyInt(pages);
  } else {
    _pages = 1;
  }
  for (let p of pyRange(1, pyAdd(_pages, 1))) {
    await d.get(`cmd=factionleague&op=2&pages=${p}`);
    data = pyAdd(data, d.findall("%&nbsp;&nbsp;(\\d+).*?opp_uin=(\\d+)"));
  }
  for (let [_, u] of pySorted(data, (x) => pyInt(x[0]))) {
    await d.get(`cmd=factionleague&op=4&opp_uin=${u}`);
    if ((contains(d.html, "勇士，"))) {
      d.log(d.find());
      if ((contains(d.html, "不幸战败"))) {
        return;
      }
    } else if ((contains(d.html, "您已阵亡"))) {
      d.log(d.find("<br /><br />(.*?)</p>"));
      return;
    }
  }
  await d.get("cmd=factionleague&op=2");
  if ((!contains(d.html, "opp_uin"))) {
    d.log("敌人已全部阵亡");
    return;
  }
}

async function 帮派黄金联赛(d) {
  await d.get("cmd=factionleague&op=0");
  if ((contains(d.html, "领取奖励"))) {
    await d.get("cmd=factionleague&op=5");
    d.log(d.find("<p>(.*?)<br /><br />"));
  } else if ((contains(d.html, "领取帮派赛季奖励"))) {
    await d.get("cmd=factionleague&op=7");
    d.log(d.find("<p>(.*?)<br /><br />"));
  } else if ((!contains(d.html, "已参与防守"))) {
    await d.get("cmd=factionleague&op=1");
    d.log(d.find("<p>(.*?)<br /><br />"));
  } else if ((contains(d.html, "休赛期"))) {
    d.log("休赛期无任何操作");
  }
  if ((contains(d.html, "op=2"))) {
    await 帮派黄金联赛_参战(d);
  }
}

register("帮派黄金联赛", 帮派黄金联赛);

async function 任务派遣中心(d) {
  await c_任务派遣中心(d);
}

register("任务派遣中心", 任务派遣中心);

async function 武林盟主(d) {
  var _id, data, index, r, s;
  if ((contains(pySet([3, 5, 7]), DateTime.week()))) {
    await d.get("cmd=wlmz&op=view_index");
    if (pyTruthy((data = d.findall("section_id=(\\d+)&amp;round_id=(\\d+)\">")))) {
      for (let [s, r] of data) {
        await d.get(`cmd=wlmz&op=get_award&section_id=${s}&round_id=${r}`);
        d.log(d.find("<br /><br />(.*?)</p>"));
      }
    } else {
      d.log("没有奖励领取");
    }
  }
  if ((contains([1, 3, 5], DateTime.week()))) {
    _id = d.config("武林盟主.id");
    if ((_id === null)) {
      d.log("你没有配置报名赛场id");
      return;
    }
    await d.get(`cmd=wlmz&op=signup&ground_id=${_id}`);
    if (((contains(d.html, "总决赛周不允许报名")) || (contains(d.html, "您的战力不足")))) {
      d.log(d.find("战报</a><br />(.*?)<br />"));
    } else if ((contains(d.html, "您已报名"))) {
      d.log(d.find("赛场】<br />(.*?)<br />"));
    }
  } else if ((contains([2, 4, 6], DateTime.week()))) {
    for (let index of pyRange(8)) {
      await d.get(`cmd=wlmz&op=guess_up&index=${index}`);
      d.log(d.find("规则</a><br />(.*?)<br />"));
    }
    await d.get("cmd=wlmz&op=comfirm");
    d.log(d.find("战报</a><br />(.*?)<br />"));
  }
}

register("武林盟主", 武林盟主);

async function 全民乱斗(d) {
  var _id, collect_status, t;
  collect_status = false;
  for (let t of [2, 3, 4]) {
    await d.get(`cmd=luandou&op=0&acttype=${t}`);
    for (let _id of d.findall(".*?id=(\\d+)\">领取</a>")) {
      collect_status = true;
      await d.get(`cmd=luandou&op=8&id=${_id}`);
      d.log(d.find("斗】<br /><br />(.*?)<br />"));
    }
  }
  if (!pyTruthy(collect_status)) {
    d.log("没有礼包领取");
  }
}

register("全民乱斗", 全民乱斗);

async function 侠士客栈(d) {
  var _id;
  await c_侠士客栈(d);
  await d.get("cmd=notice&op=view&sub=total");
  for (let _id of d.findall("giftId=(\\d+)")) {
    await d.get(`cmd=notice&op=reqreward&giftId=${_id}&sub=total`);
    d.log(d.find("<p>.*?<br />(.*?)<"));
  }
}

register("侠士客栈", 侠士客栈);

async function 江湖长梦(d) {
  var _id, exchange_config, item, material_name, quantity;
  if ((DateTime.day() !== 20)) {
    return;
  }
  exchange_config = d.config("江湖长梦.exchange");
  for (let [_id, item] of pyItems(exchange_config)) {
    material_name = item["material_name"];
    quantity = item["quantity"];
    if ((quantity <= 0)) {
      continue;
    }
    for (let _ of pyRange(quantity)) {
      await d.get(`cmd=longdreamexchange&op=exchange&key_id=${_id}`);
      if ((!contains(d.html, "成功"))) {
        d.log(`${material_name}*1 -> ${d.find()}`);
        break;
      }
      d.log(`${material_name}*1 -> ${d.find("</a><br />(.*?)<")}`);
    }
  }
}

register("江湖长梦", 江湖长梦);

async function 大侠回归(d) {
  var data, s, t;
  await d.get("cmd=newAct&subtype=173&op=1");
  if (pyTruthy((data = d.findall("subtype=(\\d+).*?taskid=(\\d+)")))) {
    for (let [s, t] of data) {
      await d.get(`cmd=newAct&subtype=${s}&op=2&taskid=${t}`);
      d.log(d.find("】<br /><br />(.*?)<br />"));
    }
  } else {
    d.log("没有礼包领取");
  }
}

register("大侠回归", 大侠回归);

async function 备战天赋(d, _id) {
  var i, start_id;
  await d.get("cmd=ascendheaven&op=viewprepare");
  start_id = d.find("id=(\\d+)");
  if ((start_id === null)) {
    return;
  }
  for (let i of pyRange(pyInt(start_id), pyAdd(_id, 1))) {
    while (pyTruthy(true)) {
      await d.get(`cmd=ascendheaven&op=activeskill&id=${i}`);
      d.log(d.find());
      if ((contains(d.html, "激活心法失败"))) {
        continue;
      }
      if ((contains(d.html, "激活心法成功"))) {
        break;
      }
      return;
    }
  }
}

async function 飞升大作战(d) {
  var _id, enabled, s, t;
  enabled = d.config("飞升大作战.玄铁令.enabled");
  t = d.config("飞升大作战.type");
  _id = d.config("飞升大作战.id");
  await d.get("cmd=ascendheaven");
  if ((contains(d.html, "赛季结算中"))) {
    enabled = false;
  }
  if ((pyTruthy(enabled) && (t === 1))) {
    await d.get("cmd=ascendheaven&op=exchange&id=2&times=1");
    d.log(d.find());
  } else if ((pyTruthy(enabled) && (t === 3))) {
    await d.get("cmd=ascendheaven&op=exchange&id=2&times=1");
    d.log(d.find());
    await d.get("cmd=ascendheaven&op=exchange&id=2&times=1");
    d.log(d.find());
  }
  await d.get(`cmd=ascendheaven&op=signup&type=${t}`);
  d.log(d.find());
  if (((contains(d.html, "你报名参加了")) || (contains(d.html, "你已经报名参赛")))) {
    if (((contains(pySet([1, 3]), t)) && (_id !== null))) {
      await 备战天赋(d, _id);
    }
  } else {
    await d.get("cmd=ascendheaven&op=signup&type=2");
    d.log(d.find());
  }
  if ((DateTime.week() !== 4)) {
    return;
  }
  await d.get("cmd=ascendheaven");
  if ((!contains(d.html, "赛季结算中"))) {
    return;
  }
  await d.get("cmd=ascendheaven&op=showrealm");
  for (let s of d.findall("season=(\\d+)")) {
    await d.get(`cmd=ascendheaven&op=getrealmgift&season=${s}`);
    d.log(d.find());
  }
}

register("飞升大作战", 飞升大作战);

async function 许愿帮铺(d) {
  var _id, count, exchange_config, item, material_name, quantity, quotient;
  exchange_config = d.config("深渊之潮.exchange");
  for (let [_id, item] of pyItems(exchange_config)) {
    material_name = item["material_name"];
    quantity = item["quantity"];
    if ((quantity <= 0)) {
      continue;
    }
    if ((contains(material_name, "之书"))) {
      quotient = Math.floor(quantity / 25);
    } else {
      quotient = 0;
    }
    count = 0;
    for (let _ of pyRange(quotient)) {
      await d.get(`cmd=abysstide&op=wishexchangetimes&id=${_id}&times=25`);
      d.log(d.find());
      if ((!contains(d.html, "成功"))) {
        break;
      }
      count = pyAdd(count, 25);
    }
    for (let _ of pyRange((quantity - count))) {
      await d.get(`cmd=abysstide&op=wishexchange&id=${_id}`);
      d.log(d.find());
      if ((!contains(d.html, "成功"))) {
        break;
      }
    }
  }
}

async function 深渊之潮(d) {
  await c_帮派巡礼(d);
  await c_深渊秘境(d);
  if ((DateTime.day() === 20)) {
    await 许愿帮铺(d);
  }
}

register("深渊之潮", 深渊之潮);

async function 侠客岛(d) {
  var duration, free_refresh_count, level, min_level, name, p, pos, reward, task_name;
  await d.get("cmd=knight_island&op=viewmissionindex");
  pos = d.findall("viewmissiondetail&amp;pos=(\\d+)");
  if (!pyTruthy(pos)) {
    for (let [name, duration] of d.findall("([^<>]+?)（需要.*?任务时长：([^<]+)")) {
      d.log(`${name} -> ${duration}`);
    }
    return;
  }
  min_level = 5;
  free_refresh_count = d.find("免费刷新剩余：(\\d+)");
  if ((free_refresh_count === null)) {
    d.log("获取免费刷新剩余失败，将免费次数重置为0");
    free_refresh_count = 0;
  } else {
    free_refresh_count = pyInt(free_refresh_count);
  }
  for (let p of pos) {
    for (let _ of pyRange(20)) {
      await d.get("cmd=knight_island&op=viewmissionindex");
      reward = d.find(`pos=${p}">接受.*?任务奖励：([^<]+)`);
      await d.get(`cmd=knight_island&op=viewmissiondetail&pos=${p}`);
      task_name = d.find("([^>]+?)（");
      level = d.find("需要.*?(\\d+)级侠士");
      if ((level === null)) {
        level = "0";
      }
      d.log(`${task_name} -> ${reward}`);
      if (((pyInt(level) < min_level) && (free_refresh_count > 0))) {
        await d.get(`cmd=knight_island&op=refreshmission&pos=${p}`);
        d.log(`${task_name} -> ${d.find("斗豆）<br />(.*?)<br />")}`);
        free_refresh_count -= 1;
        continue;
      }
      await d.get(`cmd=knight_island&op=autoassign&pos=${p}`);
      d.log(`${task_name} -> ${d.find("）<br />(.*?)<br />")}`);
      if ((contains(d.html, "快速委派成功"))) {
        await d.get(`cmd=knight_island&op=begin&pos=${p}`);
        d.log(`${task_name} -> ${d.find("斗豆）<br />(.*?)<br />")}`);
        break;
      }
      if (((contains(d.html, "符合条件侠士数量不足")) && (free_refresh_count > 0))) {
        await d.get(`cmd=knight_island&op=refreshmission&pos=${p}`);
        d.log(`${task_name} -> ${d.find("斗豆）<br />(.*?)<br />")}`);
        free_refresh_count -= 1;
        continue;
      } else {
        d.log(`${task_name} -> 没有免费刷新次数了`);
        break;
      }
    }
  }
}

register("侠客岛", 侠客岛);

async function 八卦迷阵(d) {
  var _data, i, result;
  _data = ({["离"]: 1, ["坤"]: 2, ["兑"]: 3, ["乾"]: 4, ["坎"]: 5, ["艮"]: 6, ["震"]: 7, ["巽"]: 8});
  await d.get("cmd=spacerelic&op=goosip");
  result = d.find("([乾坤震巽坎离艮兑]{4})");
  if ((result === null)) {
    result = d.config("时空遗迹.八卦迷阵");
  }
  for (let i of result) {
    await d.get(`cmd=spacerelic&op=goosip&id=${_data[i]}`);
    d.log(`${i} -> ${d.find("分钟<br /><br />(.*?)<br />")}`);
    if ((!contains(d.html, "恭喜您"))) {
      break;
    }
  }
  if ((contains(d.html, "恭喜您已通关迷阵"))) {
    await d.get("cmd=spacerelic&op=goosipgift");
    d.log(d.find("分钟<br /><br />(.*?)<br />"));
  }
}

async function 遗迹商店(d) {
  var _id, exchange_config, item, material_name, quantity, quotient, remainder, t;
  exchange_config = d.config("时空遗迹.exchange");
  for (let [_id, item] of pyItems(exchange_config)) {
    material_name = item["material_name"];
    quantity = item["quantity"];
    t = item["type"];
    if ((quantity <= 0)) {
      continue;
    }
    [quotient, remainder] = pyDivmod(quantity, 10);
    for (let _ of pyRange(quotient)) {
      await d.get(`cmd=spacerelic&op=buy&type=${t}&id=${_id}&num=10`);
      d.log(`${material_name}*10 -> ${d.find("售卖区.*?<br /><br /><br />(.*?)<")}`);
      if ((!contains(d.html, "兑换成功"))) {
        break;
      }
    }
    for (let _ of pyRange(remainder)) {
      await d.get(`cmd=spacerelic&op=buy&type=${t}&id=${_id}&num=1`);
      d.log(`${material_name}*1 -> ${d.find("售卖区.*?<br /><br /><br />(.*?)<")}`);
      if ((!contains(d.html, "兑换成功"))) {
        break;
      }
    }
  }
}

async function 异兽洞窟(d) {
  var _id, _ids;
  _ids = d.config("时空遗迹.异兽洞窟");
  if ((_ids === null)) {
    d.log("你没有设置异兽洞窟id");
    return;
  }
  for (let _id of _ids) {
    await d.get(`cmd=spacerelic&op=monsterdetail&id=${_id}`);
    if ((contains(d.html, "剩余挑战次数：0"))) {
      d.log("异兽洞窟没有挑战次数");
      break;
    }
    if ((contains(d.html, "剩余血量：0"))) {
      await d.get(`cmd=spacerelic&op=saodang&id=${_id}`);
    } else {
      await d.get(`cmd=spacerelic&op=monsterfight&id=${_id}`);
    }
    d.log(d.find("次数.*?<br /><br />(.*?)&"));
    if ((contains(d.html, "请按顺序挑战异兽"))) {
      continue;
    }
    break;
  }
}

async function 悬赏任务(d) {
  var _id, data, t;
  data = [];
  for (let t of [1, 2]) {
    await d.get(`cmd=spacerelic&op=task&type=${t}`);
    data = pyAdd(data, d.findall("type=(\\d+)&amp;id=(\\d+)"));
  }
  for (let [t, _id] of data) {
    await d.get(`cmd=spacerelic&op=task&type=${t}&id=${_id}`);
    d.log(d.find("赛季任务</a><br /><br />(.*?)<"));
    if ((contains(d.html, "您未完成该任务"))) {
      continue;
    }
  }
}

async function 遗迹征伐(d) {
  var current_date, day, end_date, month, year;
  await d.get("cmd=spacerelic&op=relicindex");
  year = d.find("(\\d+)年");
  month = d.find("(\\d+)月");
  day = d.find("(\\d+)日");
  if (((year === null) || (month === null) || (day === null))) {
    d.log("获取结束日期失败");
    return;
  }
  current_date = DateTime.current_date();
  end_date = DateTime.get_offset_date(pyInt(year), pyInt(month), pyInt(day));
  if ((current_date === end_date)) {
    await d.get("cmd=spacerelic&op=task&type=1&id=1");
    d.log(d.find("赛季任务</a><br /><br />(.*?)<"));
    await d.get("cmd=spacerelic&op=getrank");
    d.log(d.find("奖励</a><br /><br />(.*?)<"));
    await 遗迹商店(d);
    return;
  }
  end_date = DateTime.get_offset_date(pyInt(year), pyInt(month), pyInt(day), 7);
  if ((current_date >= end_date)) {
    d.log("当前处于休赛期，结束前一天领取登录奖励、赛季奖励和悬赏商店兑换");
    return;
  }
  await 异兽洞窟(d);
  await d.get("cmd=spacerelic&op=bossfight");
  d.log(d.find("挑战</a><br />(.*?)&"));
  await 悬赏任务(d);
}

async function 时空遗迹(d) {
  await 八卦迷阵(d);
  await 遗迹征伐(d);
}

register("时空遗迹", 时空遗迹);

async function 世界树(d) {
  var _id, t;
  await d.get("cmd=worldtree");
  await d.get("cmd=worldtree&op=autoget&id=1");
  d.log(d.find("福宝<br /><br />(.*?)<br />"));
  async function get_id() {
    var _id, t;
    for (let t of pyRange(4)) {
      await d.get(`cmd=worldtree&op=viewweaponpage&type=${t}`);
      for (let _id of d.findall("weapon_id=(\\d+)")) {
        await d.get(`cmd=worldtree&op=setweapon&weapon_id=${_id}&type=${t}`);
        d.log(d.find("当前武器：(.*?)<"));
        return _id;
      }
    }
  }
  await d.get("cmd=worldtree&op=viewexpandindex");
  if ((!contains(d.html, "免费温养"))) {
    d.log("没有免费温养次数");
    return;
  }
  if (((contains(d.html, "weapon_id=0")) && !pyTruthy(get_id()))) {
    d.log("没有武器可选择");
    return;
  }
  await d.get("cmd=worldtree&op=viewexpandindex");
  _id = d.find("weapon_id=(\\d+)");
  await d.get(`cmd=worldtree&op=dostrengh&times=1&weapon_id=${_id}`);
  d.log(d.find("规则</a><br />(.*?)<br />"));
  d.log(`当前进度 -> ${d.find("当前进度:(.*?)<")}`);
}

register("世界树", 世界树);

async function 龙凰论武(d) {
  var _id;
  if ((1 <= DateTime.day() && DateTime.day() <= 3)) {
    _id = d.config("龙凰之境.龙凰论武.id");
    await d.get(`cmd=dragonphoenix&op=sign&zone=${_id}`);
    d.log(d.find());
  } else if ((4 <= DateTime.day() && DateTime.day() <= 25)) {
    await c_龙凰论武(d);
    await d.get("cmd=dragonphoenix&op=gift");
    d.log(d.find("/\\d+</a><br /><br />(.*?)<"));
  } else if ((DateTime.day() === 27)) {
    await d.get("cmd=dragonphoenix&op=rankreward");
    d.log(d.find("<br /><br /><br />(.*?)<"));
  }
}

async function 龙凰云集(d) {
  var _id, exchange_config, item, material_name, quantity, quotient, remainder;
  if ((DateTime.day() !== 27)) {
    return;
  }
  await d.get("cmd=dragonphoenix&op=yunji");
  for (let _id of d.findall("idx=(\\d+)")) {
    await d.get(`cmd=dragonphoenix&op=reward&idx=${_id}`);
    d.log(d.find("<br /><br /><br />(.*?)<"));
    if ((contains(d.html, "当前无可领取奖励"))) {
      break;
    }
  }
  exchange_config = d.config("龙凰之境.exchange");
  for (let [_id, item] of pyItems(exchange_config)) {
    material_name = item["material_name"];
    quantity = item["quantity"];
    if ((quantity <= 0)) {
      continue;
    }
    [quotient, remainder] = pyDivmod(quantity, 10);
    for (let _ of pyRange(quotient)) {
      await d.get(`cmd=dragonphoenix&op=buy&id=${_id}&num=10`);
      d.log(`${material_name}*10 -> ${d.find("<br /><br /><br />(.*?)<")}`);
      if ((!contains(d.html, "成功"))) {
        break;
      }
    }
    for (let _ of pyRange(remainder)) {
      await d.get(`cmd=dragonphoenix&op=buy&id=${_id}&num=1`);
      d.log(`${material_name}*1 -> ${d.find("<br /><br /><br />(.*?)<")}`);
      if ((!contains(d.html, "成功"))) {
        break;
      }
    }
  }
}

async function 龙吟破阵(d) {
  if (!pyTruthy((1 <= DateTime.day() && DateTime.day() <= 3))) {
    return;
  }
  await d.get("cmd=dragonphoenix&op=getlastreward");
  d.log(d.find("领取<br /><br />(.*?)<"));
}

async function 龙凰之境(d) {
  await 龙凰论武(d);
  await 龙凰云集(d);
  await 龙吟破阵(d);
}

register("龙凰之境", 龙凰之境);

async function 增强经脉(d) {
  var _id, count;
  await d.get("cmd=intfmerid&sub=1");
  if ((contains(d.html, "关闭"))) {
    await d.get("cmd=intfmerid&sub=19");
    d.log("传功 -> 关闭合成两次确认");
  }
  if (((contains(d.html, "取消")) && (contains(d.html, "doudou=0")))) {
    await d.get("cmd=intfmerid&sub=21&doudou=0");
    d.log("传功 -> 取消传功符不足用斗豆代替");
  }
  count = d.find("传功符</a>:(\\d+)");
  if ((count === null)) {
    d.log("传功 -> 获取传功符数量失败");
    return;
  }
  if ((pyInt(count) < 200)) {
    d.log("传功 -> 传功符数量不足200");
    return;
  }
  for (let _ of pyRange(12)) {
    await d.get("cmd=intfmerid&sub=1");
    _id = d.find("master_id=(\\d+)\">传功</a>");
    await d.get(`cmd=intfmerid&sub=2&master_id=${_id}`);
    d.log(`传功 -> ${d.find("</p>(.*?)<p>")}`);
    if ((contains(d.html, "传功符不足！"))) {
      return;
    }
    await d.get("cmd=intfmerid&sub=5");
    d.log(`传功 -> ${d.find("</p>(.*?)<p>")}`);
    await d.get("cmd=intfmerid&sub=10&op=4");
    d.log(`传功 -> ${d.find("</p>(.*?)<p>")}`);
  }
}

async function 助阵(d) {
  var _id, count, data, f_id, i, index, index_list, p;
  data = ({[1]: [0], [2]: [0, 1], [3]: [0, 1, 2], [9]: [0, 1, 2], [4]: [0, 1, 2, 3], [5]: [0, 1, 2, 3], [6]: [0, 1, 2, 3], [7]: [0, 1, 2, 3], [8]: [0, 1, 2, 3, 4], [10]: [0, 1, 2, 3], [11]: [0, 1, 2, 3], [12]: [0, 1, 2, 3], [13]: [0, 1, 2, 3], [14]: [0, 1, 2, 3], [15]: [0, 1, 2, 3], [16]: [0, 1, 2, 3], [17]: [0, 1, 2, 3], [18]: [0, 1, 2, 3, 4]});
  function* get_id_index() {
    var f_id, index, index_list;
    for (let [f_id, index_list] of pyItems(data)) {
      for (let index of index_list) {
        yield [f_id, index];
      }
    }
  }
  count = 0;
  for (let [_id, i] of get_id_index()) {
    if ((count === 3)) {
      break;
    }
    p = `cmd=formation&type=4&formationid=${_id}&attrindex=${i}&times=1`;
    for (let _ of pyRange(3)) {
      await d.get(p);
      if ((contains(d.html, "助阵组合所需佣兵不满足条件，不能提升助阵属性经验"))) {
        d.log(`助阵 -> ${d.find("<br /><br />(.*?)。")}`);
        return;
      } else if ((contains(d.html, "阅历不足"))) {
        d.log(`助阵 -> ${d.find("<br /><br />(.*?)，")}`);
        return;
      }
      d.log(`助阵 -> ${d.find()}`);
      if ((contains(d.html, "提升成功"))) {
        count = pyAdd(count, 1);
      } else if ((contains(d.html, "经验值已经达到最大"))) {
        break;
      } else if ((contains(d.html, "你还没有激活该属性"))) {
        return;
      }
    }
  }
}

async function 查看好友资料(d) {
  var uin;
  await d.get("cmd=view&type=6");
  if ((contains(d.html, "开启查看好友信息和收徒"))) {
    await d.get("cmd=set&type=1");
    d.log("查看好友 -> 开启查看好友信息和收徒");
  }
  await d.get("cmd=friendlist&page=2");
  for (let uin of d.findall("</a>\\d+.*?B_UID=(\\d+)")) {
    d.log(`查看好友 -> ${uin}`);
    await d.get(`cmd=totalinfo&B_UID=${uin}`);
  }
}

async function 兵法研习(d) {
  var _id;
  for (let _id of [21001, 2570, 21032, 2544]) {
    await d.get(`cmd=brofight&subtype=12&op=practice&baseid=${_id}`);
    d.log(`兵法 -> ${d.find("武穆遗书：\\d+个<br />(.*?)<br />")}`);
    if ((contains(d.html, "研习成功"))) {
      break;
    }
  }
}

async function 挑战陌生人(d) {
  var u;
  await d.get("cmd=friendlist&type=1");
  for (let u of pySlice(d.findall("</a>\\d+.*?B_UID=(\\d+)"), null, 4)) {
    await d.get(`cmd=fight&B_UID=${u}&page=1&type=9`);
    d.log(`挑战陌生人 -> ${d.find("删</a><br />(.*?)！")}`);
  }
}

async function 任务(d) {
  var k, task_html, v;
  task_html = await d.get("cmd=task&sub=1");
  if ((contains(task_html, "助阵"))) {
    await 助阵(d);
  }
  if ((contains(task_html, "增强经脉"))) {
    await 增强经脉(d);
  }
  if ((contains(task_html, "查看好友资料"))) {
    await 查看好友资料(d);
  }
  if ((contains(task_html, "兵法研习"))) {
    await 兵法研习(d);
  }
  if ((contains(task_html, "挑战陌生人"))) {
    await 挑战陌生人(d);
  }
  await d.get("cmd=task&sub=7");
  for (let [k, v] of d.findall("id=\\d+\">(.*?)</a>.*?>(.*?)</a>")) {
    d.log(`${k} -> ${v}`);
  }
}

register("任务", 任务);

async function 帮派供奉(d) {
  var _id, _ids;
  _ids = d.config("我的帮派.帮派供奉");
  if ((_ids === null)) {
    return;
  }
  for (let _id of _ids) {
    for (let _ of pyRange(5)) {
      await d.get(`cmd=oblation&id=${_id}&page=1`);
      if ((contains(d.html, "供奉成功"))) {
        d.log(`${_id} -> ${d.find()}`);
        continue;
      }
      d.log(`${_id} -> ${d.find("】</p><p>(.*?)<br />")}`);
      break;
    }
    if ((contains(d.html, "每天最多供奉5次"))) {
      break;
    }
  }
}

async function 帮派任务(d) {
  var _id, count, name, task_html, tasks, url;
  task_html = await d.get("cmd=factiontask&sub=1");
  tasks = ({["帮战冠军"]: "cmd=facwar&sub=4", ["查看帮战"]: "cmd=facwar&sub=4", ["查看帮贡"]: "cmd=factionhr&subtype=14", ["查看祭坛"]: "cmd=altar", ["查看踢馆"]: "cmd=facchallenge&subtype=0", ["查看要闻"]: "cmd=factionop&subtype=8&pageno=1&type=2", ["粮草掠夺"]: "cmd=forage_war"});
  for (let [name, url] of pyItems(tasks)) {
    if ((contains(task_html, name))) {
      await d.get(url);
      d.log(name);
    }
  }
  if ((contains(task_html, "帮派修炼"))) {
    count = 0;
    for (let _id of [2727, 2758, 2505, 2536, 2437, 2442, 2377, 2399, 2429]) {
      for (let _ of pyRange(4)) {
        await d.get(`cmd=factiontrain&type=2&id=${_id}&num=1&i_p_w=num%7C`);
        d.log(d.find("规则说明</a><br />(.*?)<br />"));
        if ((contains(d.html, "技能经验增加"))) {
          count = pyAdd(count, 1);
          continue;
        }
        break;
      }
      if ((count === 4)) {
        break;
      }
    }
  }
  await d.get("cmd=factiontask&sub=1");
  for (let _id of d.findall("id=(\\d+)\">领取奖励</a>")) {
    await d.get(`cmd=factiontask&sub=3&id=${_id}`);
    d.log(d.find("日常任务</a><br />(.*?)<br />"));
  }
}

async function 我的帮派(d) {
  var sub, subs;
  await d.get("cmd=factionop&subtype=3&facid=0");
  if ((!contains(d.html, "你的职位"))) {
    d.log("您还没有加入帮派");
    return;
  }
  await 帮派供奉(d);
  await 帮派任务(d);
  if ((DateTime.week() !== 7)) {
    return;
  }
  if (pyTruthy(d.config("我的帮派.帮战.enabled"))) {
    subs = [4, 9, 6];
  } else {
    subs = [4, 6];
  }
  for (let sub of subs) {
    await d.get(`cmd=facwar&sub=${sub}`);
    d.log(d.find("</p>(.*?)<br /><a.*?查看上届"));
  }
}

register("我的帮派", 我的帮派);

async function 帮派祭坛(d) {
  var _id, all_disbanded, data, op;
  await d.get("cmd=altar");
  for (let _ of pyRange(30)) {
    if ((contains(d.html, "转动轮盘"))) {
      await d.get("cmd=altar&op=spinwheel");
      if ((contains(d.html, "转动轮盘"))) {
        d.log(d.find());
      }
      if (((contains(d.html, "转转券不足")) || (contains(d.html, "已达转转券转动次数上限")))) {
        return;
      }
    }
    if ((contains(d.html, "【随机分配】"))) {
      all_disbanded = true;
      data = d.findall("op=(.*?)&amp;id=(\\d+)");
      for (let [op, _id] of data) {
        await d.get(`cmd=altar&op=${op}&id=${_id}`);
        if ((contains(d.html, "选择路线"))) {
          await d.get(`cmd=altar&op=dosteal&id=${_id}`);
        }
        if (((contains(d.html, "该帮派已解散")) || (contains(d.html, "系统繁忙")))) {
          d.log(d.find("<br /><br />(.*?)<br />"));
          continue;
        }
        all_disbanded = false;
        if ((contains(d.html, "转动轮盘"))) {
          d.log(d.find());
          break;
        }
      }
      if ((pyTruthy(all_disbanded) && pyTruthy(data))) {
        return;
      }
    }
    if ((contains(d.html, "领取奖励"))) {
      await d.get("cmd=altar&op=drawreward");
      d.log(d.find());
    }
  }
}

register("帮派祭坛", 帮派祭坛);

async function 每日奖励(d) {
  var key;
  for (let key of ["login", "meridian", "daren", "wuzitianshu"]) {
    await d.get(`cmd=dailygift&op=draw&key=${key}`);
    d.log(d.find());
  }
}

register("每日奖励", 每日奖励);

async function 领取徒弟经验(d) {
  await d.get("cmd=exp");
  d.log(d.find("每日奖励</a><br />(.*?)<br />"));
}

register("领取徒弟经验", 领取徒弟经验);

async function 今日活跃度(d) {
  var action, actions, activity_level, has_task_15, has_task_16, num;
  await d.get("cmd=liveness");
  if (pyTruthy((activity_level = d.find("今日活跃度：(\\d+)")))) {
    num = pyInt(activity_level);
    if ((num < 80)) {
      has_task_15 = (contains(d.html, "15.[0/1]"));
      has_task_16 = (contains(d.html, "16.[0/3]"));
      actions = [];
      if (((num >= 77) && pyTruthy(has_task_16))) {
        actions.push(助阵);
      } else if (((num >= 75) && pyTruthy(has_task_15))) {
        actions.push(增强经脉);
      } else if (((num >= 72) && pyTruthy(has_task_15) && pyTruthy(has_task_16))) {
        actions.push(...[助阵, 增强经脉]);
      }
      if (pyTruthy(actions)) {
        d.log(activity_level);
        for (let action of actions) {
          await action(d);
        }
      }
    }
  }
  await c_领取今日活跃度奖励(d);
}

register("今日活跃度", 今日活跃度);

async function 仙武修真(d) {
  var _id, count, task_id;
  for (let task_id of pyRange(1, 4)) {
    await d.get(`cmd=immortals&op=getreward&taskid=${task_id}`);
    d.log(d.find("帮助</a><br />(.*?)<br />"));
  }
  count = d.find("剩余挑战次数：(\\d+)");
  if ((count === null)) {
    d.log("获取挑战次数失败");
    return;
  }
  for (let _ of pyRange(pyInt(count))) {
    _id = randomChoice([1, 2, 3]);
    await d.get(`cmd=immortals&op=visitimmortals&mountainId=${_id}`);
    d.log(d.find("帮助</a><br />(.*?)<"));
    d.log(`本次寻访：${d.find("本次寻访：.*?>(.*?)<")}`);
    await d.get("cmd=immortals&op=fightimmortals");
    d.log(d.find("帮助</a><br />(.*?)<"));
  }
}

register("仙武修真", 仙武修真);

async function 乐斗黄历(d) {
  await d.get("cmd=calender&op=2");
  d.log(d.find("<br /><br />(.*?)<br />"));
  await d.get("cmd=calender&op=4");
  d.log(d.find("<br /><br />(.*?)<br />"));
}

register("乐斗黄历", 乐斗黄历);

async function 器魂附魔(d) {
  var _id;
  for (let _id of pyRange(1, 4)) {
    await d.get(`cmd=enchant&op=gettaskreward&task_id=${_id}`);
    d.log(d.find());
  }
}

register("器魂附魔", 器魂附魔);

async function 兵法(d) {
  var _id, remainder, t, u;
  if ((DateTime.week() === 4)) {
    await d.get("cmd=brofight&subtype=13");
    _id = d.find("teamid=(\\d+).*?助威</a>");
    await d.get(`cmd=brofight&subtype=13&teamid=${_id}&type=5&op=cheer`);
    d.log(d.find("领奖</a><br />(.*?)<br />"));
  }
  if ((DateTime.week() !== 6)) {
    return;
  }
  await d.get("cmd=brofight&subtype=13&op=draw");
  d.log(d.find("领奖</a><br />(.*?)<br />"));
  for (let t of pyRange(1, 6)) {
    await d.get(`cmd=brofight&subtype=10&type=${t}`);
    for (let [remainder, u] of d.findall("50000.*?(\\d+).*?champion_uin=(\\d+)")) {
      if ((remainder === "0")) {
        continue;
      }
      await d.get(`cmd=brofight&subtype=10&op=draw&champion_uin=${u}&type=${t}`);
      d.log(d.find("排行</a><br />(.*?)<br />"));
      return;
    }
  }
}

register("兵法", 兵法);

function* get_boss_id() {
  var _id;
  for (let _id of pyRange(6394, 6013, (-20))) {
    yield _id;
    yield (_id - 1);
  }
}

async function 点亮(d) {
  var c_id, cushaw_id;
  await d.get("cmd=hallowmas&gb_id=1");
  while (pyTruthy(true)) {
    if (pyTruthy((cushaw_id = d.findall("cushaw_id=(\\d+)")))) {
      c_id = randomChoice(cushaw_id);
      await d.get(`cmd=hallowmas&gb_id=4&cushaw_id=${c_id}`);
      d.log(d.find());
      if ((contains(d.html, "活力"))) {
        return true;
      }
    }
    if ((contains(d.html, "请领取今日的活跃度礼包来获得蜡烛吧"))) {
      break;
    }
  }
  return false;
}

async function 点亮南瓜灯(d) {
  var _id, count;
  await d.get("cmd=view&type=6");
  if ((contains(d.html, "取消自动使用活力药水"))) {
    await d.get("cmd=set&type=11");
    d.log("取消自动使用活力药水");
  }
  for (let _id of get_boss_id()) {
    count = 3;
    while (pyTruthy(count)) {
      await d.get(`cmd=mappush&subtype=3&npcid=${_id}&pageid=2`);
      if ((contains(d.html, "您还没有打到该历练场景"))) {
        d.log(d.find("介绍</a><br />(.*?)<br />"), "历练");
        break;
      }
      d.log(d.find("\\d+<br />(.*?)<"), "历练");
      if ((contains(d.html, "活力不足"))) {
        if (!pyTruthy(await 点亮(d))) {
          return;
        }
        continue;
      } else if ((!contains(d.html, "BOSS"))) {
        break;
      }
      count -= 1;
    }
  }
}

async function 万圣节(d) {
  var day, end_date, month;
  await 点亮南瓜灯(d);
  await d.get("cmd=hallowmas");
  [month, day] = d.findall("(\\d+)月(\\d+)日6点")[0];
  end_date = DateTime.get_offset_date(DateTime.year(), pyInt(month), pyInt(day));
  if ((DateTime.current_date() === end_date)) {
    await d.get("cmd=hallowmas&gb_id=6");
    d.log(d.find());
    await d.get("cmd=hallowmas&gb_id=5");
    d.log(d.find());
  }
}

register("万圣节", 万圣节);

async function 乐斗能量(d) {
  var _id, count, data;
  await d.get("cmd=newAct&subtype=108&op=0");
  data = d.findall("id=(\\d+)");
  if (!pyTruthy(data)) {
    d.log("没有可领取的能量棒");
    return;
  }
  await d.get("cmd=view&type=6");
  if ((contains(d.html, "取消自动使用活力药水"))) {
    await d.get("cmd=set&type=11");
    d.log("取消自动使用活力药水");
  }
  for (let _id of get_boss_id()) {
    count = 3;
    while (pyTruthy(count)) {
      await d.get(`cmd=mappush&subtype=3&npcid=${_id}&pageid=2`);
      if ((contains(d.html, "您还没有打到该历练场景"))) {
        d.log(d.find("介绍</a><br />(.*?)<br />"), "历练");
        break;
      }
      d.log(d.find("\\d+<br />(.*?)<"), "历练");
      if ((contains(d.html, "活力不足"))) {
        if (!pyTruthy(data)) {
          return;
        }
        await d.get(`cmd=newAct&subtype=108&op=1&id=${data.pop()}`);
        d.log(d.find("<br /><br />(.*?)<"));
        continue;
      } else if ((!contains(d.html, "BOSS"))) {
        break;
      }
      count -= 1;
    }
  }
}

register("乐斗能量", 乐斗能量);

async function 大笨钟(d) {
  await c_大笨钟(d);
}

register("大笨钟", 大笨钟);

async function 幸运金蛋(d) {
  await c_幸运金蛋(d);
}

register("幸运金蛋", 幸运金蛋);

async function 客栈同福(d) {
  await c_客栈同福(d);
}

register("客栈同福", 客栈同福);

async function 反向历练(d, link_text) {
  var _id;
  if (!pyTruthy(d.config(`${link_text}.历练.enabled`))) {
    return;
  }
  await d.get("cmd=view&type=6");
  if ((contains(d.html, "开启自动使用活力药水"))) {
    await d.get("cmd=set&type=11");
    d.log("历练 -> 开启自动使用活力药水");
  }
  for (let _id of get_boss_id()) {
    for (let _ of pyRange(3)) {
      await d.get(`cmd=mappush&subtype=3&mapid=6&npcid=${_id}&pageid=2`);
      if ((contains(d.html, "您还没有打到该历练场景"))) {
        d.log(`历练 -> ${d.find("介绍</a><br />(.*?)<br />")}`);
        break;
      }
      d.log(`历练 -> ${d.find("阅历值：\\d+<br />(.*?)<br />")}`);
      if (((contains(d.html, "活力不足")) || (contains(d.html, "活力药水使用次数已达到每日上限")))) {
        return;
      } else if ((!contains(d.html, "BOSS"))) {
        break;
      }
    }
  }
}

register("反向历练", 反向历练);

async function 节日福利(d) {
  await 反向历练(d, "节日福利");
}

register("节日福利", 节日福利);

async function 双旦福利(d) {
  await 反向历练(d, "双旦福利");
}

register("双旦福利", 双旦福利);

async function 金秋福利(d) {
  await 反向历练(d, "金秋福利");
}

register("金秋福利", 金秋福利);

async function 春节福利(d) {
  await 反向历练(d, "春节福利");
}

register("春节福利", 春节福利);

async function 多倍福利(d) {
  await 反向历练(d, "多倍福利");
}

register("多倍福利", 多倍福利);

async function 新春拜年(d) {
  var i;
  await d.get("cmd=newAct&subtype=147");
  if ((contains(d.html, "op=1"))) {
    for (let i of randomSample(pyRange(5), 3)) {
      await d.get(`cmd=newAct&subtype=147&op=1&index=${i}`);
    }
    await d.get("cmd=newAct&subtype=147&op=2");
    d.log("已赠礼");
  }
}

register("新春拜年", 新春拜年);

const __globals = { 邪神秘宝: 邪神秘宝, 华山论剑: 华山论剑, 分享: 分享, 好友: 好友, 帮友: 帮友, 侠侣: 侠侣, 武林: 武林, 群侠: 群侠, 结拜: 结拜, 巅峰之战进行中: 巅峰之战进行中, 矿洞: 矿洞, 掠夺: 掠夺, 踢馆: 踢馆, 竞技场: 竞技场, 十二宫: 十二宫, 许愿: 许愿, 抢地盘: 抢地盘, 历练: 历练, 镖行天下: 镖行天下, 幻境: 幻境, 群雄逐鹿: 群雄逐鹿, 画卷迷踪: 画卷迷踪, 门派: 门派, 门派邀请赛: 门派邀请赛, 会武: 会武, 梦想之旅: 梦想之旅, 问鼎天下_商店兑换: 问鼎天下_商店兑换, 问鼎天下_助威: 问鼎天下_助威, 问鼎天下: 问鼎天下, 帮派商会: 帮派商会, 帮派远征军_攻击: 帮派远征军_攻击, 帮派远征军_领取: 帮派远征军_领取, 帮派远征军: 帮派远征军, 帮派黄金联赛_参战: 帮派黄金联赛_参战, 帮派黄金联赛: 帮派黄金联赛, 任务派遣中心: 任务派遣中心, 武林盟主: 武林盟主, 全民乱斗: 全民乱斗, 侠士客栈: 侠士客栈, 江湖长梦: 江湖长梦, 大侠回归: 大侠回归, 备战天赋: 备战天赋, 飞升大作战: 飞升大作战, 许愿帮铺: 许愿帮铺, 深渊之潮: 深渊之潮, 侠客岛: 侠客岛, 八卦迷阵: 八卦迷阵, 遗迹商店: 遗迹商店, 异兽洞窟: 异兽洞窟, 悬赏任务: 悬赏任务, 遗迹征伐: 遗迹征伐, 时空遗迹: 时空遗迹, 世界树: 世界树, 龙凰论武: 龙凰论武, 龙凰云集: 龙凰云集, 龙吟破阵: 龙吟破阵, 龙凰之境: 龙凰之境, 增强经脉: 增强经脉, 助阵: 助阵, 查看好友资料: 查看好友资料, 兵法研习: 兵法研习, 挑战陌生人: 挑战陌生人, 任务: 任务, 帮派供奉: 帮派供奉, 帮派任务: 帮派任务, 我的帮派: 我的帮派, 帮派祭坛: 帮派祭坛, 每日奖励: 每日奖励, 领取徒弟经验: 领取徒弟经验, 今日活跃度: 今日活跃度, 仙武修真: 仙武修真, 乐斗黄历: 乐斗黄历, 器魂附魔: 器魂附魔, 兵法: 兵法, get_boss_id: get_boss_id, 点亮: 点亮, 点亮南瓜灯: 点亮南瓜灯, 万圣节: 万圣节, 乐斗能量: 乐斗能量, 大笨钟: 大笨钟, 幸运金蛋: 幸运金蛋, 客栈同福: 客栈同福, 反向历练: 反向历练, 节日福利: 节日福利, 双旦福利: 双旦福利, 金秋福利: 金秋福利, 春节福利: 春节福利, 多倍福利: 多倍福利, 新春拜年: 新春拜年 };
export { 邪神秘宝, 华山论剑, 分享, 好友, 帮友, 侠侣, 武林, 群侠, 结拜, 巅峰之战进行中, 矿洞, 掠夺, 踢馆, 竞技场, 十二宫, 许愿, 抢地盘, 历练, 镖行天下, 幻境, 群雄逐鹿, 画卷迷踪, 门派, 门派邀请赛, 会武, 梦想之旅, 问鼎天下_商店兑换, 问鼎天下_助威, 问鼎天下, 帮派商会, 帮派远征军_攻击, 帮派远征军_领取, 帮派远征军, 帮派黄金联赛_参战, 帮派黄金联赛, 任务派遣中心, 武林盟主, 全民乱斗, 侠士客栈, 江湖长梦, 大侠回归, 备战天赋, 飞升大作战, 许愿帮铺, 深渊之潮, 侠客岛, 八卦迷阵, 遗迹商店, 异兽洞窟, 悬赏任务, 遗迹征伐, 时空遗迹, 世界树, 龙凰论武, 龙凰云集, 龙吟破阵, 龙凰之境, 增强经脉, 助阵, 查看好友资料, 兵法研习, 挑战陌生人, 任务, 帮派供奉, 帮派任务, 我的帮派, 帮派祭坛, 每日奖励, 领取徒弟经验, 今日活跃度, 仙武修真, 乐斗黄历, 器魂附魔, 兵法, get_boss_id, 点亮, 点亮南瓜灯, 万圣节, 乐斗能量, 大笨钟, 幸运金蛋, 客栈同福, 反向历练, 节日福利, 双旦福利, 金秋福利, 春节福利, 多倍福利, 新春拜年 };
